### ISSUE TITLE
Freezes / Application is not responding

### ISSUE THREAD

**Issue by Tycho-X** [gerstrong/Commander-Genius#211]
Hello,

the app keeps freezing a lot on my Ouya with Android 4.1.2. Latest freeze happend after loading keen 1 saved games but it also freezes during game and change of levels. Here is logact excerpt:
-----------
I/Commander Genius(11511): n: File "/mnt/usbdrive/keen/SaveData/save/games/keen1/cksave1.ck1" was sucessfully loaded. Size: 10391
I/InputDispatcher(  322): Application is not responding: AppWindowToken{4194ffa8 token=Token{419c45f0 ActivityRecord{4160d8f8 net.sourceforge.clonekeenplus/.MainActivity}}} - Window{418b4fa0 net.sourceforge.clonekeenplus/net.sourceforge.clonekeenplus.MainActivity paused=false}.  It has been 5001.2ms since event, 5000.9ms since wait started.  Reason: Waiting because the focused window has not finished processing the input events that were previously delivered to it.
I/WindowManager(  322): Input event dispatching timed out sending to net.sourceforge.clonekeenplus/net.sourceforge.clonekeenplus.MainActivity
E/ActivityManager(  322): ANR in net.sourceforge.clonekeenplus (net.sourceforge.clonekeenplus/.MainActivity)
E/ActivityManager(  322):   93% 11511/net.sourceforge.clonekeenplus: 90% user + 3.2% kernel / faults: 24973 minor
E/ActivityManager(  322):   101% 11511/net.sourceforge.clonekeenplus: 100% user + 1.9% kernel
W/ActivityManager(  322):   Force finishing activity net.sourceforge.clonekeenplus/.MainActivity
I/ActivityManager(  322): Killing ProcessRecord{419232d0 11511:net.sourceforge.clonekeenplus/u0a95}: user's request
I/ActivityManager(  322): Process net.sourceforge.clonekeenplus (pid 11511) has died.
I/WindowState(  322): WIN DEATH: Window{418b4fa0 net.sourceforge.clonekeenplus/net.sourceforge.clonekeenplus.MainActivity paused=true}
-----------

Unluckily i dont know how to attach the complete app log.

cheers,

  Arnd

**Comment by gerstrong** [comment]
Closing this due inactivity
