### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Jayman2000** [gerstrong/Commander-Genius#212]
I'm running Win 7 x64 and whenever I try to launch Commander Genius I get this:
![image](https://cloud.githubusercontent.com/assets/5579359/5331648/aedc59c4-7e01-11e4-9999-fe4c56fc26a6.png)
I'm running 1.8.1.1

**Comment by gerstrong** [comment]
Updated was uploaded here: http://sourceforge.net/projects/clonekeenplus/files/CGenius/V1.8/CGenius-1.8.1.3-Release-win32.zip/download

It has some bug fixes and the dlls bundled. Closing this issue. If it still doesn't work, reopen this one :-)
