### ISSUE TITLE
Retropie

### ISSUE THREAD

**Issue by delMar43** [gerstrong/Commander-Genius#214]
Hi,
thanks for creating this, really!

I know that the libretro topic has already been talked about briefly here https://github.com/gerstrong/Commander-Genius/issues/172 but I think it's missing what libretro is all about.

To make it short: I, personally would love to play Commander Genius on a gaming console with a controller without having to start it via a keyboard command or a double-click on some desktop. Also I really prefer to not having to configure controllers, etc.

Retropie http://blog.petrockblock.com/retropie/ is just that:
My personal gaming console based on Raspberry Pi. I can play Duke Nukem 3D, most ScummVM games and lots of old, emulated stuff.
Retropie / Libretro would allow exactly that for Commander Genius. A completely console-like gaming experience from console boot 'till 'Game Over'

That's it.

Sorry for bringing this up again, no offense intended at all.
And thanks for keeping the Commander alive!!!

**Comment by juanmabc** [comment]
What about implementing a libretro backend for SDL?

**Comment by gerstrong** [comment]
Doesn't libretro already use SDL? I thought it was a wrapper which optionally uses SDL.

**Comment by juanmabc** [comment]
< Martin original desire: To make it short: I, personally would love to
play Commander Genius on a gaming console with a controller without having
to start it via a keyboard command or a double-click on some desktop. Also
I really prefer to not having to configure controllers, etc. >

Commander Genius For Android Launches Like That.

**Comment by RobLoach** [comment]
While it targets Lua, [Lutro](https://github.com/Kivutar/libretro-lutro) is a small framework that Kivutar put together to build games for libretro. Might be a good place to look for inspiration.

**Comment by gerstrong** [comment]
Yeah, why not. If someone wants to do it, I'm fine with it. I cannot create a port of that right now. It's just a matter of time and priorites set on the project.
