### ISSUE TITLE
Network Stack

### ISSUE THREAD

**Issue by Zombie-Ryushu** [gerstrong/Commander-Genius#215]
Is there any way we could add a standard TCP/IP network stack to Commander Genius's multiplayer capabilities? I'd like to be able to network multiple Linux builds of Commander Genius with different players able to act autonomously to their own display yet function in a Collaborative manner.

**Comment by gerstrong** [comment]
Hi, this is something I'm going to extend when the SDL 2 support on Android is complete. Only the overlay input and compilation is missing. SDL 1.2 already works. So you might expect that soon.

**Comment by Zombie-Ryushu** [comment]
The idea is that while I love the fact I can play with 4 players, I can't normally have that 4 player setup be completely local. I'd like options for UDP connection port to be dynamic, and the ability to mix local and remote users.

**Comment by gerstrong** [comment]
Yeah, that is exactly, what we plan...

Am 30.01.2015 um 17:39 schrieb Zombie-Ryushu:

**Comment by Zombie-Ryushu** [comment]
Perfect.

**Comment by Zombie-Ryushu** [comment]
Is there any progress on this?

**Comment by gerstrong** [comment]
No, not yet!

Am 08.01.2016 um 09:51 schrieb Zombie-Ryushu:

**Comment by gerstrong** [comment]
This won't happen very soon, since lack of resources for that huge changes.
