### ISSUE TITLE
Android .apk download on http://clonekeenplus.sourceforge.net/download/

### ISSUE THREAD

**Issue by cweiske** [gerstrong/Commander-Genius#217]
I own an Ouya console which is based on Android, but does not have the google play store. Thus I have to download the `.apk` manually and put it then on the Ouya via USB.

Unfortunately, the download page at http://clonekeenplus.sourceforge.net/download/ does not offer a link to the .apk file but only links to the google play store.

I'd really like to see the direct .apk download link there.

**Comment by gerstrong** [comment]
Just found out, that I need to fix that link. There is an APK you can download and pretty up to date.

http://sourceforge.net/projects/clonekeenplus/files/CGenius/V1.8/

I will be creating those for future versions
