### ISSUE TITLE
Wormouth impossible to shoot

### ISSUE THREAD

**Issue by najawa** [gerstrong/Commander-Genius#218]
The frames in which Wormouth goes from a pea to his full form are immediately fatal, eliminating the expected reaction time needed to kill him. The frames in which he's appearing, I need to be able to get a shot off (this is just under keen normal - he could be hypothetically more difficult in the harder modes).

Thanks!

**Comment by gerstrong** [comment]
Hi Najawa,

just trying this out in hardmode. I can shoot the wormmouth at any time. Maybe you need to shoot him jumping over the enemy and shooting down. Even being in pea frame this works. 

I remember in the original Keen it was hard to shoot this guy so mostly I tried to avoid him.

In normal difficulty the behavoir is the same and higher difficulties make the guy move faster, that is all.

I'll leave this ticket open, maybe you can provide me more feedback, telling what is going from your perspective wrong in Commander Genius.

Thanks for reporting!

**Comment by gerstrong** [comment]
Closing this...
