### ISSUE TITLE
Tearing still present even with OpenGL and Vsync set to on 

### ISSUE THREAD

**Issue by Blackbird88** [gerstrong/Commander-Genius#222]
Using latest stable version on W8.1 x64

**Comment by gerstrong** [comment]
That one is hard to test. I'll take a look later on this ...

**Comment by Blackbird88** [comment]
Dunno how can I help. Basically when the screen moves the tearing is still there.
Maybe **Tripple buffering** would help?

**Comment by gerstrong** [comment]
Let me take a review on OpenGL and SDL 2.0 again. I think the bug is in 
our code or maybe in one of those libs...

Am 02.07.2015 um 14:17 schrieb Blackbird88:

**Comment by gerstrong** [comment]
well, I have updated CG to 1.8.2.1, but those issue is still open for me...

**Comment by Blackbird88** [comment]
It seems to be gone from what I've seen.

**Comment by gerstrong** [comment]
Btw. I also mentioned your guide here: 

http://www.pckf.com/viewtopic.php?p=76006&sid=9d90fe9548c0e3f8bee134f9fae49548#76006

I really liked it!

**Comment by Blackbird88** [comment]
Heh no problem. It annoyed me that there was no simple guide to make it Steam-compatible as I talk to some of my friends through the overlay.

Also just compared old release with new one and it's definitely gone. It was mostly noticeable in Keen 1-3 games. Gave me headache sometimes :D

**Comment by gerstrong** [comment]
If this issue is not present for you, you can close it. I haven't had any issues with screen tearing in this game.

**Comment by Blackbird88** [comment]
Alright sure thing. Thanks for fixing it btw.
