### ISSUE TITLE
Keen 3 - Final boss undefeatable?

### ISSUE THREAD

**Issue by Blackbird88** [gerstrong/Commander-Genius#223]
I destroyed all those purple glowing things and nothing happens. Only screen shake :/

**Comment by gerstrong** [comment]
Did you use the latest version? At least for the next upcoming release that issue is not reproduceable. Closing this...

**Comment by Blackbird88** [comment]
Of course I used last version.

**Comment by gerstrong** [comment]
Okay, in my case it disappears and I get the ending as supposed to be. So maybe somehow in the engines changes it got fixed. At least in the master branch it works correctly.

**Comment by Blackbird88** [comment]
So did you test it only in latest git version? I don't use those. Only stable.

**Comment by gerstrong** [comment]
Well yes, because this master stable enough right now. I performed some tests today. After some more tests within the next days another release. So I consider it fixed.

**Comment by Blackbird88** [comment]
Great! Will report back if the issue persists :)

**Comment by Blackbird88** [comment]
Yup it is fixed.
