### ISSUE TITLE
Keen 1-3 - Can't see previous save when saving

### ISSUE THREAD

**Issue by Blackbird88** [gerstrong/Commander-Genius#225]
You save a game.
You want to save again.
The slot is EMPTY.

This also makes it so you can't save from controller since you have to retype it all the time :(

**Comment by gerstrong** [comment]
Haven't taken a look for time on that. Let me test this. Still supposing you used Windows and version 1.8.2

**Comment by Blackbird88** [comment]
Oh of course I forgot.

**Comment by gerstrong** [comment]
fixed bdc9de50eadeaec62eaa576ba9d4991fa8544537
