### ISSUE TITLE
git source doesn't build: needs pregenerated README file

### ISSUE THREAD

**Issue by ildar** [gerstrong/Commander-Genius#228]
trivial:
> CMake Error at /usr/share/CMake/Modules/CPack.cmake:393 (message):
>   CPack package description file:
>   "/usr/src/RPM/BUILD/Commander-Genius-1.8.3/README" could not be found.
> Call Stack (most recent call first):
>   /usr/share/CMake/Modules/CPack.cmake:397 (cpack_check_file_exists)

**Comment by gerstrong** [comment]
Another small issue fixed 74234dcdb83173deb8968e16d080c0a570918faf
