### ISSUE TITLE
undefined reference to `gDreamsForceClose'

### ISSUE THREAD

**Issue by ildar** [gerstrong/Commander-Genius#229]
> Linking CXX executable CGeniusExe
> ../lib/GsKit/libGsKit.a(CInput.cpp.o): In function `CInput::resetControls(int)':
> /usr/src/RPM/BUILD/Commander-Genius-1.8.3/lib/GsKit/base/CInput.cpp:81: undefined reference to `gDreamsForceClose'
> /usr/src/RPM/BUILD/Commander-Genius-1.8.3/lib/GsKit/base/CInput.cpp:81: undefined reference to `gDreamsForceClose'
> ../lib/GsKit/libGsKit.a(CInput.cpp.o): In function `CInput::pollEvents()':
> /usr/src/RPM/BUILD/Commander-Genius-1.8.3/lib/GsKit/base/CInput.cpp:771: undefined reference to `gDreamsForceClose'
> /usr/src/RPM/BUILD/Commander-Genius-1.8.3/lib/GsKit/base/CInput.cpp:605: undefined reference to `gDreamsForceClose'
> collect2: error: ld returned 1 exit status

configuration phase says:
> -- Refkeen for Keen Dreams: OFF

**Comment by gerstrong** [comment]
You are right! Thanks for noticing

I just fixed it! 28afd7a0fe4c763241af848ba3878ccb33f823b5

Refkeen has been not that hard to port, but a lot of work is still going on...
