### ISSUE TITLE
Cross building for Raspberry Pi

### ISSUE THREAD

**Issue by vanfanel** [gerstrong/Commander-Genius#239]
Hi,

I'm trying to cross-build this for the Raspberry Pi, 
I have the crosscompiler (arm-bcm2708hardfp-linux-gnueabi) installd and working, and the raspbian libraries (including SDL2 2.0.4 and the others) copied over to a local directory, but I can't figure out where to specify the crosscompiler to use and the libraries and includes path.
@gerstrong Can you lend a hand? I'm sure you know the buildsystem pretty well.

**Comment by ildar** [comment]
>
> AFAIR CG uses cmake. You should look at cross building with cmake before
anything else.
But actually you'd better not cross build at all: just find a binary for
your architecture, e.g. in Debian repos (or where it could be).

> Also build natively may be a good idea. Find out how to build in a qemu.
-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by gerstrong** [comment]
Hi @ildar ,

I'm not sure if I can help you. I know about the build system, but I don't know anything about your environment.

Cross building usually implies the use of another compiler that must exist in your system for another target system. You can indicate that compiler with the CMAKE_CXX_COMPILER and CMAKE_C_COMPILER. 

I think it is easier to compile the stuff on Rasperry Pi and let cmake detect what you have there. Is that possible?

If not maybe another environment on your system with chroot could help on this. Because if you cross-build programs you will have to indicate another compiler and other library paths and the correct libs to link against. These libs must work on your target system.

So tell me, what is your preferred way and I might tell you more...

**Comment by ildar** [comment]
@gerstrong, that wasn't me who was asking, that was Manuel Alfayate Corchete

**Comment by gerstrong** [comment]
H @ildar, you are right my bad, the message is for you @vanfanel

**Comment by vanfanel** [comment]
@gerstrong 
It's easier to build on the Pi, but it's an SLOW process and having it cross-compiling we could generate new versions very fast for the Pi.
Also, I have a distcc enviroment working, but it's failing to build CG and I don't now why (distcc only says compilation has failed and retries locally, but compilation on the Pi eventually eats up all the RAM and I have no swapfile), so I want to cross-compile locally on the host machine to see what's the problem.

Well, I have been doing some research and this is what I get so far.
First I export the path with the arm cross-compiler:
`
PATH=$PATH:$HOME/tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/bin `

`  
Then I have created a toolchain file with these contents (the target system usr,lib,and opt directories from Raspbian are in /opt/rpi_root):

`
# this one is important
SET(CMAKE_SYSTEM_NAME Linux)
#this one not so much
SET(CMAKE_SYSTEM_VERSION 1)

# specify the cross compiler
SET(CMAKE_C_COMPILER   arm-bcm2708hardfp-linux-gnueabi-gcc)
SET(CMAKE_CXX_COMPILER arm-bcm2708hardfp-linux-gnueabi-g++)

# where is the target environment 
SET(CMAKE_FIND_ROOT_PATH  /opt/rpi_root)

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
`

The I use cmake like this, passing the toolchain file to it:

`
cmake  -DUSE_SDL2=yes -DBUILD_TARGET=LINUX -DCMAKE_BUILD_TYPE=Release -DOGG=no -DTREMOR=NO -DOPENGL=no -DREFKEEN=no -DCMAKE_TOOLCHAIN_FILE=~/src/raspi.cmake ..
`

It results on the buildsystem to find everything alright, apparently:

`
manuel@vader:~/src/Commander-Genius/b3$ cmake  -DUSE_SDL2=yes -DBUILD_TARGET=LINUX -DCMAKE_BUILD_TYPE=Release -DOGG=no -DTREMOR=NO -DOPENGL=no -DREFKEEN=no -DCMAKE_TOOLCHAIN_FILE=~/src/raspi.cmake ..
-- cotire 1.7.6 loaded.
-- Preparing the Build-System for Commander Genius
-- Setting SYSTEM_DATA_DIR to /usr/share/games
-- Using shared SDL Version 2 for Commander Genius
-- Boost version: 1.55.0
-- Using shared SDL Version 2 for Commander Genius
-- DOSBox-Fusion: OFF
-- Internal Downloader: OFF
-- Refkeen for Keen Dreams: no
-- CPACK_PACKAGE_VERSION = 1.9.1-Beta
-- Build system is prepared. To Build the project just type "make"
-- If you want to create the installation package just type "make package" after you build the project
-- Configuring done
-- Generating done
-- Build files have been written to: /home/manuel/src/Commander-Genius/b3
manuel@vader:~/src/Commander-Genius/b3$ cd ..
manuel@vader:~/src/Commander-Genius$ sudo rm -R b3
manuel@vader:~/src/Commander-Genius$ mkdir build
manuel@vader:~/src/Commander-Genius$ cd build/
manuel@vader:~/src/Commander-Genius/build$ cmake  -DUSE_SDL2=yes -DBUILD_TARGET=LINUX -DCMAKE_BUILD_TYPE=Release -DOGG=no -DTREMOR=NO -DOPENGL=no -DREFKEEN=no -DCMAKE_TOOLCHAIN_FILE=~/src/raspi.cmake ..
-- The C compiler identification is GNU 4.7.1
-- The CXX compiler identification is GNU 4.7.1
-- Check for working C compiler: /home/manuel/tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/bin/arm-bcm2708hardfp-linux-gnueabi-gcc
-- Check for working C compiler: /home/manuel/tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/bin/arm-bcm2708hardfp-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/manuel/tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/bin/arm-bcm2708hardfp-linux-gnueabi-g++
-- Check for working CXX compiler: /home/manuel/tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/bin/arm-bcm2708hardfp-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.7.6 loaded.
-- Preparing the Build-System for Commander Genius
-- Setting SYSTEM_DATA_DIR to /usr/local/
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for one of the modules 'sdl2'
-- Using shared SDL Version 2 for Commander Genius
-- Boost version: 1.55.0
-- checking for one of the modules 'SDL2_image>=2.0.0'
-- Using shared SDL Version 2 for Commander Genius
-- DOSBox-Fusion: OFF
-- Internal Downloader: OFF
-- Refkeen for Keen Dreams: no
-- CXX target CGeniusExe cotired.
-- CPACK_PACKAGE_VERSION = 1.9.1-Beta
-- Build system is prepared. To Build the project just type "make"
-- If you want to create the installation package just type "make package" after you build the project
-- Configuring done
-- Generating done
-- Build files have been written to: /home/manuel/src/Commander-Genius/build
`

Then when I try to build it, there are problems with header file location:

`
[ 14%] Building CXX object src/graphics/CMakeFiles/graphics.dir/effects/CColorMerge.cpp.o
In file included from /usr/include/SDL2/SDL_stdinc.h:40:0,
                 from /usr/include/SDL2/SDL_main.h:25,
                 from /usr/include/SDL2/SDL.h:32,
                 from /home/manuel/src/Commander-Genius/src/graphics/effects/CColorMerge.h:14,
                 from /home/manuel/src/Commander-Genius/src/graphics/effects/CColorMerge.cpp:8:
/opt/rpi_root/usr/include/stdlib.h:760:34: fatal error: bits/stdlib-bsearch.h: No such file or directory
compilation terminated.
src/graphics/CMakeFiles/graphics.dir/build.make:54: recipe for target 'src/graphics/CMakeFiles/graphics.dir/effects/CColorMerge.cpp.o' failed
make[2]: *** [src/graphics/CMakeFiles/graphics.dir/effects/CColorMerge.cpp.o] Error 1
CMakeFiles/Makefile2:1213: recipe for target 'src/graphics/CMakeFiles/graphics.dir/all' failed
make[1]: *** [src/graphics/CMakeFiles/graphics.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2
`

That particular file is present in the target root system:
`
manuel@vader:~/src/Commander-Genius/build$ find /opt/rpi_root/usr/include -name stdlib-bsearch.h
/opt/rpi_root/usr/include/arm-linux-gnueabihf/bits/stdlib-bsearch.h
`

...but it seems the buildsystem does not look for headers in that arm-linux-gnueabihf subdirectory.
How can I convince it to do so? I am almost there! :)

**Comment by ildar** [comment]
> I am almost there! :)
I doubt that, sorry ;)

As I wrote:
> Also build natively may be a good idea. Find out how to build in a qemu.
That means building on a PC but in qemu-emulated environment, like in your
Pi. Find out how to build in it...

**Comment by gerstrong** [comment]
Hi, I have been cleaning up a lot lately. I have a device here. Might test it later that day...

**Comment by gerstrong** [comment]
Closing this, for what I heard it is fixed
