### ISSUE TITLE
Build Fails on Raspberry Pi

### ISSUE THREAD

**Issue by HerbFargus** [gerstrong/Commander-Genius#243]
Here is the build log: http://pastebin.com/2iC5BUnJ

Just for reference I'm using a Raspberry Pi 2 with RetroPie.

Happy to provide more details if needed.

**Comment by gerstrong** [comment]
Hi @HerbFargus sorry for the late reply. Were you able to solve your problem?

**Comment by HerbFargus** [comment]
I haven't tested it extensively. Something is likely crashing GCC rather than something wrong in the coding so I need to test with more swap or something. I was able to get release 1.8.0 to compile just fine but GCC crashed when I attempted to build anything newer than that.
