### ISSUE TITLE
XInput

### ISSUE THREAD

**Issue by gerstrong** [gerstrong/Commander-Genius#247]
I have some suggestions. It seems like this engine does not support xinput, but rather use the old directinput option. Nowadays I don't suppose people use directinput gamepads that often, as the Xbox 360/Xbox One controller is the standard when it comes to PC gaming. 

It's no big issue when only binding one gamepad to this engine, but as Commander Genius supports up to four players simultaneous, I would have to rebind the controls each time I'm playing with multiple friends. It is a common "bug" in all directinput games when you use multiple wireless Xbox 360/Xbox One gamepads.

**Comment by gerstrong** [comment]
http://blog.5pmcasual.com/game-controller-api-in-sdl2.html

**Comment by cRaZy-bisCuiT** [comment]
Yes please, get us XInput.

**Comment by gerstrong** [comment]
Nice idea, but I have no 360 xbox gamepad, I can add some functions but have no chance to test it.

**Comment by gerstrong** [comment]
Please reopen, if it does not work. The API should support it since v2.6
