### ISSUE TITLE
Improve game selection UI

### ISSUE THREAD

**Issue by akien-mga** [gerstrong/Commander-Genius#252]
I've just updated my commandergenius package for Mageia, but I'm still having a hard time enjoying it due to the (IMO) bad UX when starting it for the first time. It may come from the way I package it (for example I delete the vfsroot folder because I don't want to distribute nonfree data), but upon starting the program, a user of my package will see:

![spectacle j15394](https://cloud.githubusercontent.com/assets/4701338/14228573/f2dd3eca-f918-11e5-852c-7964c6a6a6c9.png)

Problems:
- the window is ridiculously tiny. Not counting the title bar, it's 320x200 px, which might be fitting for handheld devices like the GCW Zero, but not for desktop; the program should detect the platform and use a better fitting resolution.
- the actual content is even smaller, 210x170 px or something like that. Why that empty black space around it? At this size, the font is hardly readable.
- there is no option to import games data/define a data path - this was requested already in #230, but I'd like to insist on the fact that it's _really_ needed for a good UX.

Sorry for making this a relatively vague issue, as a developer I know that those are not the most useful to work with, but I felt it was worth mentioning here and I don't have much time to dig deeper myself.

**Comment by gerstrong** [comment]
I have to agree. For next time the standard will be double in both directions to 640x400 on desktop systems. Actually there exist bigger fonts and better looking fonts, so this won't be a big deal. Thanks for porting to Mageia, btw. :-)

**Comment by Tamsyn** [comment]
I agree - I don't even know how to import the games I have.  I want to play these games - I own these games, I have commander genius.  Now what?  Your UX should make this obvious, or at least not so obscure.

**Comment by gerstrong** [comment]
Is it really "oscure" if it is mentioned in the readme file? Seriously...

**Comment by Tamsyn** [comment]
It wasn't on the download page, or visible within the download.  For you and me, who are used to looking on github for answers, no.  For most users, I think so.

**Comment by gerstrong** [comment]
Actually the readme is displayed on the project github page but you have a good point and it is not the first time someone complains about this issue. I want to rework the webpage anyways and I will consider putting more documentation especially for people on android and who want to get their own games run.

**Comment by akien-mga** [comment]
Don't forget people install CG from their distro's package manager, which rarely shows the upstream readme in an obvious manner (it is typically installed in `/usr/share/doc/<name>/README`).

IMO, a good UI and UX when loading CG with no configured game is a must. The minimal would be that it displays in a non-ridiculous size on desktop (see OP), and gives information about how to install and configure games. A second step would be to add some logic to let users install and configure their games out of the box (e.g. "Browse to your Commander Keen 4 installation folder"), but that could be handled in a separate issue.

**Comment by ildar** [comment]
Good point. Sorry, @gerstrong, I agree.
CG is fairly usable so it should be as easy to set up as to play it.

**Comment by gerstrong** [comment]
I have added a lot of new error messages and more feedback for the user. 

@akien-mga: I think I have fulfilled your observation regarding: 

> IMO, a good UI and UX when loading CG with no configured game is a must. The minimal would be that it displays in a non-ridiculous size on desktop (see OP), and gives information about how to install and configure games. A second step would be to add some logic to let users install and configure their games out of the box (e.g. "Browse to your Commander Keen 4 installation folder"), but that could be handled in a separate issue.

First of all there is a game store. User gets a warning if the catalog file is missing. It should be there by default, since it is considered in our scripts.

Secondly if there are no games another warning is shown with the recommendation to copy games or just let them download with CG internal download manager. It lot has changed there lately.

Version 1.9.9.6 handles it much better than ever before. Let me know what you think.. :-) Closing this issue...

**Comment by ildar** [comment]
👍
I'll test it next week.

**Comment by ildar** [comment]
Yep, tested, very satisfied.

**Comment by ildar** [comment]
keen1 and keen4 miss preview images when installed.

**Comment by gerstrong** [comment]
Thanks, normally they get generated  after the game was started. Some bundles already have these included. They are called preview.png. But not later than after one game start the preview image should appear.
