### ISSUE TITLE
High Quality Pack volume is not uniform

### ISSUE THREAD

**Issue by Danfun64** [gerstrong/Commander-Genius#255]
There are cases where the Sound Blaster sound effects in the Voritcon Saga aren't as loud as they are with pc speaker. Another example is in Keen 4, where the music used in the first level is louder than it is without the pack.

**Comment by gerstrong** [comment]
I have been leveleing the volume of the packs a bit. I'm considering removing those packs anyways, now that you have the downloadable content for each Keen game.
