### ISSUE TITLE
GsKit dependency fails to build on nixos due to wrong SDL include path

### ISSUE THREAD

**Issue by hce** [gerstrong/Commander-Genius#256]
nixos (https://nixos.org) has a functional approach to package management. Each library residess in a non-standard directory. GsKit does not use sdl-config/sdl2-config to determine the correct paths for the sdl include directories.

cmake runs fine:

    [nix-shell:~/builds/Commander-Genius]$ cmake -DUSE_SDL2=yes -DBUILD_TARGET=LINUX
    [...]
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/hc/builds/Commander-Genius

make eventually brings this problem:
    /home/hc/builds/Commander-Genius/lib/GsKit/base/video/CVideoEngine.h:14:17: fatal error: SDL.h: No such file or directory

sdl2-config output:
    [nix-shell:~/builds/Commander-Genius]$ sdl2-config --cflags
    -I/nix/store/m46gj08gp2vdrb4p1hbfclz5lx2phzbn-SDL2-2.0.3/include/SDL2 -D_REENTRANT

    [nix-shell:~/builds/Commander-Genius]$ ls -l /nix/store/m46gj08gp2vdrb4p1hbfclz5lx2phzbn-SDL2-2.0.3/include/SDL2/SDL.h 
    -r--r--r-- 1 root root 5374 Jan  1  1970 /nix/store/m46gj08gp2vdrb4p1hbfclz5lx2phzbn-SDL2-2.0.3/include/SDL2/SDL.h

**Comment by hce** [comment]
Fixed this locally by appending to GsKit's CMakeLists.txt the following lines:

    execute_process(COMMAND sdl2-config --cflags
      OUTPUT_VARIABLE CFLAGS)
    string(REGEX REPLACE "^-I" "" CFLAGS2 ${CFLAGS})
    string(REGEX REPLACE " .*" "" SDLINC ${CFLAGS2})
    INCLUDE_DIRECTORIES(${SDLINC})

**Comment by gerstrong** [comment]
I don't quite understand what you are trying to do but the compilation never failed here. GsKit is so far for CG only so you should built together with that project. 

Anyways, I have added a script in that project env. so SDL is configured as it should. Let me know if it works and reopen this ticket in contrary case. 10a2d2c

You fix, well is an option but we have been happy with pkg-config

Btw. interesting Linux distribution you are working on. Wish you the best!

**Comment by hce** [comment]
Jup, your fix seems to work as well. Thanks!

**Comment by hce** [comment]
Just FYI, commander genius is now available in nixos  ( https://github.com/NixOS/nixpkgs/pull/16948 )
