### ISSUE TITLE
Black Screen on Startup

### ISSUE THREAD

**Issue by Terrapin2190** [gerstrong/Commander-Genius#257]
(Copied from a thread I created in the Public Commander Keen Forum)
http://www.pckf.com/viewtopic.php?p=80895#80895

I'm not sure if this has been discussed before. I did a quick browse through the first page and didn't see anything related.

I've been using Commander Genius v1.8.3 and have encountered a black screen upon startup of the application. Not getting to the game selection screen even. Sometimes it will exit when I press 'Enter,' other times I will have to press Alt+F4.

Last I remember, I was playing Keen 4 and I had modified the resolution settings. I used 320x200 as the game's display area and 1360x768 as the actual display resolution. Now, my monitor's native res is 1366x768.

Other miscellaneous options I changed were control configuration (with an Aftershock AP.1 PS3 controller) and there were a few others I changed that were unrelated to display. 

I've also 'installed' (via .zip extraction method) CG v1.9.5 (had to manually install libcurl.dll, libeay32.dll, and ssleay32.dll) into a separate folder and still encountered the error. From there, I searched through regedit for anything related (and readable with my personal tech knowledge) to CG, but haven't found anything that will fix it yet.

I am using Windows 7 x64.

This happens when trying to use another version as well. (Extracted into a separate folder)

Also, I'm not seeing the cgenius.cfg file anywhere.

Thanks for reading. I'm hoping to get this sorted out so I can get back to playing through Keen 4-9.

**Comment by gerstrong** [comment]
Hi Terrapin2190,

I noticed that lately, but was a bit busy with other things. I try to get back to that and update the whole CG with other improvements as soon as possible. The dlls will be shipped as well, my oversought... :-)

I think the next version will be 1.9.5.3 for that purpose.

**Comment by gerstrong** [comment]
On a Windows System you normally find the cgenius.cfg under "Documents\Commander Genius" with all the other stuff. It is possible that it still needs to be created though.

I just updated to Beta 1.9.5.3. It should be better now. Let know if you still encounter problems
