### ISSUE TITLE
More configuration in Android App

### ISSUE THREAD

**Issue by gerstrong** [gerstrong/Commander-Genius#264]
wie kann man denn bei Ihrem Spiel unter Android die Steuerung verändern? Ich habe ein Bluetooth-Gamepad an meinem Tablet, welches ich gerne verwenden möchte. Leider gibt es aus naheliegenden Gründen nicht die Möglichkeit, die Taste "F3" zu drücken.

**Comment by FromCrimsonToWool** [comment]
Hacker's keyboard should give you access to an F3 key https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=en

**Comment by gerstrong** [comment]
In the latest version 1.9.9.0 you can freely assign the commands


Regards

- Gerd

**Comment by gerstrong** [comment]
I have refined this, closing
