### ISSUE TITLE
Build fails in Arch Linux

### ISSUE THREAD

**Issue by JPLeBreton** [gerstrong/Commander-Genius#265]
Near the end of compilation, I get this error:
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGLU.so', needed by 'src/CGeniusExe'.  Stop.

My system has this file, but it's at /usr/lib/libGLU.so; seems like the build process might be assuming an Ubuntu-like configuration

I can work around this by symlinking libGLU.so and libGL.so to the expected location from /usr/lib.

**Comment by gerstrong** [comment]
I think you should add another LINK_DIRECTORIES Path. If you use cmake it should detect those automatically. I find your problem strange, because I have been using Arch Linux and it works with that change. 

Did you try cleaning CMake caches?

Sorry for the late reply...
