### ISSUE TITLE
[FR] Secret Agent

### ISSUE THREAD

**Issue by Purity666** [gerstrong/Commander-Genius#266]
Good morning,

did anyone check the possibility to implement support for Apogee's Secret Agent? I've seen a request for Dangerous Dave but to me the engine used by Secret Agent (which is originally the one of Crystal Caves I think) looks more similiar to the first three Commander Keen Episodes. Is this somewhere on the agenda or did anyone even start on this?

Greetings
Purity

**Comment by gerstrong** [comment]
Sorry, but chances are very bad for additional games since a lot of the core members have left the team. I will maintain some minor updates and bug fixes, but for other dos games I need more help...
