### ISSUE TITLE
Hud in vorticon Keen Not fully rendern in android

### ISSUE THREAD

**Issue by gerstrong** [gerstrong/Commander-Genius#272]
Only Text with White bkg is seen. Borders and Icons are missing

**Comment by Kasijjuf** [comment]
Could you please provide a screenshot? On most devices running Android holding down the [Power] and [Volume Down] buttons will save a screenshot to the photo gallery.

**Comment by gerstrong** [comment]
What. Do you want to fix it? I do Not recommend that. Let me Take a look.

**Comment by gerstrong** [comment]
Fixed
