### ISSUE TITLE
Keen's 4 5 and 6 won't start

### ISSUE THREAD

**Issue by hoover1979** [gerstrong/Commander-Genius#274]
Hi.  I am trying to get commander genius to work with my steam copy (keens 1-5) and my old disk copy of keen 6 I had since the 90's keens 1, 2 and 3 work fine but 4, 5 and 6 don't start, there is no title pic in the commander genius menu and selevting keens 4-6 crashes out the prgram with no error message.

**Comment by gerstrong** [comment]
Strange, Steam Versions are supported. Did you Take a look at cglog.html?

**Comment by hoover1979** [comment]
I don's seem to have a cglog.,html anywhere in my Commander Genius install.  

I am using the v1.9.9.2 beta.  keens 1,2 and 3 work fine and in the CG menu on the right side has an image of the title screens as logois.  4, 5 and 6 don't run, don't have any title screens as logos on the right side of the CG menu, and just close CG when I select them.  1,2,3,4 and 5 are from Steam and my copy of keen 6 I have had since the 90's.

Maybe I need to revert to the older 1x versions to see if this is an issue with the new beta?

**Comment by gerstrong** [comment]
Hi Hover, there must be CGLog.html somewhere. If you are on Windows take a look at the Documents directory then CommanderGenius. I don't think that you need an older Version. Steam versions are the Last ones ever released. It must be something different.Am 03.09.2017 3:10 vorm. schrieb hoover1979 <notifications@github.com>:I don's seem to have a cglog.,html anywhere in my Commander Genius install.
I am using the v1.9.9.2 beta.  keens 1,2 and 3 work fine and in the CG menu on the right side has an image of the title screens as logois.  4, 5 and 6 don't run, don't have any title screens as logos on the right side of the CG menu, and just close CG when I select them.  1,2,3,4 and 5 are from Steam and my copy of keen 6 I have had since the 90's.
Maybe I need to revert to the older 1x versions to see if this is an issue with the new beta?

**Comment by gerstrong** [comment]
Hi hoover1979,
just uploaded an update, version 1.9.9.5. Can you try that one? Let me know what CGLog.html has to say :-)

**Comment by hoover1979** [comment]
I downloaded your new version (1.9.9.5 beta), and installed it and when I tried to run and I get this error when trying to run it all I got was this error message:.

"CGenius.exe - System Error

The program can't start because python35.dll is missing from your computer.  Try reinstalling the program to fix this problem"

This "python35.dll" doesn't seem to be part of the install, nor is it part of the 1.9.9.2 beta install.  
I don't want to go to some .dll file site as they can have .dll files injected with malware.

if you are able to recompile a download with this missing file, can you let me know which files from keens 4 5 and 6 are needed to install, keens 1-5 are lumped together in one folder in Steam and years ago I threw keen 6 in there as well. so they are all in one place.  I wonder if a file is missing 

For exemple for keen 4 I think I just have the Keen4.exe, File_ID.diz and all the .ck4 files.

**Comment by gerstrong** [comment]
Ahh okay, good to know. Yeah, I need to bundle that then. Didn't notice it got missing. I find it strange that there is a python36.dll. Let me check that. Keen 4-6 has python support, that is why it crashes. No, renaming that file is not a good idea, let me see what's wrong...

**Comment by gerstrong** [comment]
Okay, I have uploaded version 1.9.9.6 some days ago. It contains a stable and fitting Python 3.5 setup. The Keen now should run correctly. Can you let me know if that is the case?

**Comment by hoover1979** [comment]
Yes I can get all 6 keens working.  Keen 6 didn't work untill I patched it to 1.4 but all is good now.  Now I just need to find a version of Keen Dreams that works.

**Comment by gerstrong** [comment]
Hi hoover1979. Do you have the game store working.
There you let CG download two Commander Keen Dreams. The first one is the original, the other called Plus has better graphics and other levels. Very fun to play.

**Comment by hoover1979** [comment]
Game Store?  I am using Commander Genius on Windows so the only game stores I have are Steam Origin Uplay and GoG Keen Dreams was on Steam but it was pulled along with some other titles because the Dev had a nervous breakdown and ran amok, including bullying a revier fro Abrams Tank and shaming him on the store page., but changing the company title to "Gayben's flatulent ***hole" was the last straw and Valve was forced to take action.  

Unless there is a store hidden in the CG client that I haven't found yet, if so please elaborate?

**Comment by gerstrong** [comment]
When you open the launcher, you have the option to choose to choose a game or there is a button calls "+ More". If you click on that button it open another page where you can pull games. There you find Dreams and Dreams Plus. It looks like in this video where Keen 4 Plus is being tested:

https://www.youtube.com/watch?v=5YjD0cACpZk

**Comment by hoover1979** [comment]
O.K. I downloaded both Keen Dreams and Keen Dreams Plus.

The problem with both of these titles is they run in slow motion.  keen 1-6 run smooth as silk at 120FPS and Keen Dreams runs like the speed has been halved (rather than the FPS the timer seems to be halved)

**Comment by gerstrong** [comment]
Keen Dreams uses different engine so called RefKeen. Unfortunately it bases a bit on the original dos code. If I get time I will dissolve that. Is it the FPS or is the overall gameplay much slower? Original Keen games had lower FPS anyways, but ran fast enough... Keen Dreams might use less FPS but should playable enough for now...  Is that the case...?

**Comment by hoover1979** [comment]
it is lower game speed, not lower FPS

**Comment by gerstrong** [comment]
Yeah, that's a different problem. I'm working on it...

**Comment by gerstrong** [comment]
Hi, I improved the Dreams engine a bit. Let me know if it better now, at least since 166d9061 Revison.

**Comment by hoover1979** [comment]
I will try it out tomorrow and let you know how it goes.  Thank you very much for the support you have given.  AAA game devs need to learn from your example!

**Comment by hoover1979** [comment]
Sorry I couldn't test it sooner as I was in hospital.  I downladed the latest version of Commander genius.  there seems to be no difference in Keen Dreams in regards to slow mo, but keen dreams plus crashes the program .

Here is the event log


Faulting application name: CGenius.exe, version:0.0.0.0, time stamp 0x00030000
Faulting module name: CGenius.exe, version:0.0.0.0, time stamp 0x00030000
Exception code: 0xc00000005
Fault offset: 0x001db98b
Faulting process id: 0x45ec
Faulting application start time: 0x01d33e53549e199
Faulting application path c:\games\keen 3\CGenius.exe
Faulting module path: C:\games\keen 3\CGenius.exe
Report Id: 750c1d82-aa4d-11e7-ba94-ff39ca504c7d

**Comment by gerstrong** [comment]
Did you compile it? My changes are only coded but not yet built for win32. Still fixing other bugs for the next upload...Am 06.10.2017 6:29 vorm. schrieb hoover1979 <notifications@github.com>:Sorry I couldn't test it sooner as I was in hospital.  I downladed the latest version of Commander genius.  there seems to be no difference in Keen Dreams in regards to slow mo, but keen dreams plus crashes the program .
Here is the event log
Faulting application name: CGenius.exe, version:0.0.0.0, time stamp 0x00030000
Faulting module name: CGenius.exe, version:0.0.0.0, time stamp 0x00030000
Exception code: 0xc00000005
Fault offset: 0x001db98b
Faulting process id: 0x45ec
Faulting application start time: 0x01d33e53549e199
Faulting application path c:\games\keen 3\CGenius.exe
Faulting module path: C:\games\keen 3\CGenius.exe
Report Id: 750c1d82-aa4d-11e7-ba94-ff39ca504c7d

**Comment by hoover1979** [comment]
That explains it, the changes aren't in the current version for download.  Thanks for clarifying it.
