### ISSUE TITLE
commander Genius on Retropie: what commands to type to get it installed, etc?

### ISSUE THREAD

**Issue by Jondark** [gerstrong/Commander-Genius#276]
I have been unable to get Commander Genius to install on Retropie--which is running Ubuntu or so I am told.  I tried typing commands listed on the CG page--but it does not appear to install.

How do I get it up & running on Retropie?  Very specific step-by-step directions would be needed as I am not a computer programmer and Ubuntu sounds like what a pitcher in baseball does to get to 1st base... 

I would love to get it running & for my grown kids, who are Commander Keen fans... 

Also, would this be able to play the Cosmo games (all were from Apogee in the past, all seem to have installed the same)...

I am hoping this can be done!

Thanks!

**Comment by gerstrong** [comment]
For what I understand there is an experimental repository where you can install CG. Did you try that? Last time I checked RetroPie there was an older but working version. The developers behind RetroPie have been very active updating it. Which commands do you mean? In the README there also are some instructions...

**Comment by gerstrong** [comment]
Unfortunately there is no support for Cosmos Cosmic and for the next time I don't think there will be.

**Comment by Jondark** [comment]
Hi;

 

Thank you for the response.  Do you have any idea where the esperimental repository is?  I had tried following the various instructions, modifications, but I couldn’t even get it to copy to the hard drive using sudo command listed on the main site…

 

Evan

**Comment by Jondark** [comment]
Ha—thanks for the hint.  Found CGenius on experimental setup.  Never thought to look there 😊

 

Thank you!

 

Evan
