### ISSUE TITLE
[Feature request] Unlimited framerate

### ISSUE THREAD

**Issue by vanfanel** [gerstrong/Commander-Genius#279]
Hi, 

In the past, I have commented how CG shows small "hiccups" even in 60FPS mode on a 60Hz display.
Other source ports, like GZDoom, have an "unlimited framerate" option that make them absolutely perfect.
With this option ON, the game should NOT do ANY framerate calculations. Nothing. Just let it run *as fast as possible*.
That, combined with VSYNC ON (which should pass SDL_RENDERER_PRESENTVSYNC to SDL_CreateRenderer to work), would make the game run synchronized to physical display rate, thus resulting in an always perfect scroll as long as the CPU can cope.

Could you please add such an option? Implementation is easy: just skip all framerate calculations as I said (delays, etc.) and pass the SDL_RENDER_PRESENTVSYNC flag to SDL_CreateRenderer().

**Comment by gerstrong** [comment]
hi @vanfanel, I reworked the code a bit. Now there is a switch where you can switch FrameSkip on or off. 
The SDL_RENDER_PRESENTVSYNC flag is already in the code and turned on when vsync option is on. ac29ad4b
