### ISSUE TITLE
Problem building latest git revision

### ISSUE THREAD

**Issue by vanfanel** [gerstrong/Commander-Genius#280]
Hi, Gerstrong

I was trying to build in order to test that new option to disable frame skipping totally, but I can't:

```
pi@raspberrypi:~/src/Commander-Genius/b3 $ cmake  -DUSE_SDL2=ON -DBUILD_TARGET=LINUX -DCMAKE_BUILD_TYPE=Release -DDBFUSION=OFF -DTREMOR=OFF -DOPENGL=OFF -DDOWNLOADER=OFF ../          
-- Preparing the Build-System for Commander Genius
-- Setting SYSTEM_DATA_DIR to /usr/share/games
-- SDLIMAGE INCLUDE DIR /usr/include/SDL2
-- SDLIMAGE_LIBRARY /usr/lib/libSDL2_image.so
CMake Error at CMakeLists.txt:115 (add_subdirectory):
  The source directory

    /home/pi/src/Commander-Genius/GsKit

  does not contain a CMakeLists.txt file.



```

Do you have any idea on what's going on? I used to build with no problems with that cmake line.

**Comment by gerstrong** [comment]
in the sources you need to:

git submodule init
git submodule update

After that it should work. I need to put this into the readme

**Comment by vanfanel** [comment]
This one can be closed, but I agree, the submodule stuff should be added to the readme :)

**Comment by gerstrong** [comment]
I already did that the last days. Thanks for testing and giving feedback ☺Am 29.10.2017 9:10 nachm. schrieb The Last Cabra <notifications@github.com>:This one can be closed, but I agree, the submodule stuff should be added to the readme :)
