### ISSUE TITLE
Keen 6 enemies are ignoring Keen

### ISSUE THREAD

**Issue by levinnd** [gerstrong/Commander-Genius#299]
In Keen 6 giks ignore Keen and do not attack him. Normal bloogs also ignore Keen and do not chase him when he jumps them. There may be more enemies that ignore Keen.

**Comment by levinnd** [comment]
I observed this on the android app, which otherwise I thi k is fantastic.

**Comment by gerstrong** [comment]
Let me check the original behavior. There seems to be more of it.

**Comment by gerstrong** [comment]
It is better for the upcoming release as of 76b6e4dc
