### ISSUE TITLE
Guard robots getting stuck in walls

### ISSUE THREAD

**Issue by levinnd** [gerstrong/Commander-Genius#301]
In Keen 2 the guard robots can get stuck on walls and be unable to turn. I observed this on the android app in engine room b.

**Comment by gerstrong** [comment]
Okay, got it. Give me time to look this over.

**Comment by gerstrong** [comment]
Not in the upcoming, but there were collision fixes. If the problems in the next update, please reopen this ticket.

**Comment by levinnd** [comment]
I just tested the new android release. Its still there.

**Comment by gerstrong** [comment]
Can you show me an example? Which level, screenshot?

**Comment by levinnd** [comment]
Engine Room B. Its getting stuck against the right purple wall. You can see it heading there and then it gets stuck. I'd give you a screenshot but I dont know how to do screenshots on this.

**Comment by gerstrong** [comment]
Cannot reproduce on 3.4.9. Feel free to reopen this ticket if you find another robots going through walls.
