### ISSUE TITLE
Again unable to build from git

### ISSUE THREAD

**Issue by vanfanel** [gerstrong/Commander-Genius#302]
@gerstrong : Building from git is broken again:

```
[ 18%] Building CXX object src/engine/core/CMakeFiles/engine_core.dir/CHUD.cpp.o
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp: In member function ‘void CHUD::setup(int)’:
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp:74:34: error: ‘class GsSprite’ has no member named ‘smartSDLSurface’; did you mean ‘getSDLSurface’?
         auto HUDBoxSfc = mHUDBox.smartSDLSurface();
                                  ^~~~~~~~~~~~~~~
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp: In member function ‘void CHUD::CreateVorticonBackground()’:
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp:112:45: error: ‘class GsSprite’ has no member named ‘smartSDLSurface’; did you mean ‘getSDLSurface’?
     auto keenHeadSmartSfc = mKeenHeadSprite.smartSDLSurface();
                                             ^~~~~~~~~~~~~~~
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp:137:43: error: ‘class GsSprite’ has no member named ‘smartSDLSurface’; did you mean ‘getSDLSurface’?
     auto keenGunSmartSfc = mKeenGunSprite.smartSDLSurface();
                                           ^~~~~~~~~~~~~~~
src/engine/core/CMakeFiles/engine_core.dir/build.make:134: recipe for target 'src/engine/core/CMakeFiles/engine_core.dir/CHUD.cpp.o' failed
make[2]: *** [src/engine/core/CMakeFiles/engine_core.dir/CHUD.cpp.o] Error 1
CMakeFiles/Makefile2:577: recipe for target 'src/engine/core/CMakeFiles/engine_core.dir/all' failed
make[1]: *** [src/engine/core/CMakeFiles/engine_core.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

Maybe it would be a good idea if you would try to build before pushing updates? :)

**Comment by gerstrong** [comment]
My bad sorry, just give me a couple of minutes to fix that. Am 30.12.2017 7:01 nachm. schrieb The Last Cabra <notifications@github.com>:@gerstrong : Building from git is broken again:
[ 18%] Building CXX object src/engine/core/CMakeFiles/engine_core.dir/CHUD.cpp.o
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp: In member function ‘void CHUD::setup(int)’:
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp:74:34: error: ‘class GsSprite’ has no member named ‘smartSDLSurface’; did you mean ‘getSDLSurface’?
auto HUDBoxSfc = mHUDBox.smartSDLSurface();
^~~~~~~~~~~~~~~
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp: In member function ‘void CHUD::CreateVorticonBackground()’:
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp:112:45: error: ‘class GsSprite’ has no member named ‘smartSDLSurface’; did you mean ‘getSDLSurface’?
auto keenHeadSmartSfc = mKeenHeadSprite.smartSDLSurface();
^~~~~~~~~~~~~~~
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp:137:43: error: ‘class GsSprite’ has no member named ‘smartSDLSurface’; did you mean ‘getSDLSurface’?
auto keenGunSmartSfc = mKeenGunSprite.smartSDLSurface();
^~~~~~~~~~~~~~~
src/engine/core/CMakeFiles/engine_core.dir/build.make:134: recipe for target 'src/engine/core/CMakeFiles/engine_core.dir/CHUD.cpp.o' failed
make[2]: *** [src/engine/core/CMakeFiles/engine_core.dir/CHUD.cpp.o] Error 1
CMakeFiles/Makefile2:577: recipe for target 'src/engine/core/CMakeFiles/engine_core.dir/all' failed
make[1]: *** [src/engine/core/CMakeFiles/engine_core.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
Maybe it would be a good idea if you would try to build before pushing updates? :)

**Comment by gerstrong** [comment]
okay, it should build again. There are some graphical glitches, but more secure code. Fixing those right now...
