### ISSUE TITLE
Unable tu build again

### ISSUE THREAD

**Issue by vanfanel** [gerstrong/Commander-Genius#303]
@gerstrong : I really believe you should build before pushing, you will save time in the end:

```
[ 18%] Building CXX object src/engine/core/CMakeFiles/engine_core.dir/CHUD.cpp.o
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp: In member function ‘void CHUD::CreateVorticonBackground()’:
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp:94:24: error: ‘class GsSprite’ has no member named ‘empty’
     if(mKeenHeadSprite.empty())
                        ^~~~~
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp:98:46: error: ‘class GsSprite’ has no member named ‘Surface’; did you mean ‘mpSurface’?
     auto &keenHeadSmartSfc = mKeenHeadSprite.Surface();
                                              ^~~~~~~
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp:115:39: error: ‘class GsSprite’ has no member named ‘Surface’; did you mean ‘mpSurface’?
     auto &keenGunSfc = mKeenGunSprite.Surface();
                                       ^~~~~~~
src/engine/core/CMakeFiles/engine_core.dir/build.make:134: recipe for target 'src/engine/core/CMakeFiles/engine_core.dir/CHUD.cpp.o' failed
make[2]: *** [src/engine/core/CMakeFiles/engine_core.dir/CHUD.cpp.o] Error 1
CMakeFiles/Makefile2:577: recipe for target 'src/engine/core/CMakeFiles/engine_core.dir/all' failed
make[1]: *** [src/engine/core/CMakeFiles/engine_core.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2


```

**Comment by gerstrong** [comment]
I did build before. I think your GsKit sources are outdated. Did you git submodule update after pulling? I need to automate that somehow...Am 31.12.2017 2:11 vorm. schrieb The Last Cabra <notifications@github.com>:@gerstrong : I really believe you should build before pushing, you will save time in the end:
[ 18%] Building CXX object src/engine/core/CMakeFiles/engine_core.dir/CHUD.cpp.o
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp: In member function ‘void CHUD::CreateVorticonBackground()’:
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp:94:24: error: ‘class GsSprite’ has no member named ‘empty’
     if(mKeenHeadSprite.empty())
                        ^~~~~
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp:98:46: error: ‘class GsSprite’ has no member named ‘Surface’; did you mean ‘mpSurface’?
     auto &keenHeadSmartSfc = mKeenHeadSprite.Surface();
                                              ^~~~~~~
/home/manuel/src/Commander-Genius/src/engine/core/CHUD.cpp:115:39: error: ‘class GsSprite’ has no member named ‘Surface’; did you mean ‘mpSurface’?
     auto &keenGunSfc = mKeenGunSprite.Surface();
                                       ^~~~~~~
src/engine/core/CMakeFiles/engine_core.dir/build.make:134: recipe for target 'src/engine/core/CMakeFiles/engine_core.dir/CHUD.cpp.o' failed
make[2]: *** [src/engine/core/CMakeFiles/engine_core.dir/CHUD.cpp.o] Error 1
CMakeFiles/Makefile2:577: recipe for target 'src/engine/core/CMakeFiles/engine_core.dir/all' failed
make[1]: *** [src/engine/core/CMakeFiles/engine_core.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vanfanel** [comment]
@gerstrong : Since the git version now builds fine (after manual "git submodule update"!) I am closing this issue.
