### ISSUE TITLE
Video Quality setting is not saved

### ISSUE THREAD

**Issue by vanfanel** [gerstrong/Commander-Genius#304]
Hi,

I have noticed the VIDEO->QUALITY setting (NEAREST/LINEAR) is not saved. It's a very simple problem, but it would be useful to have it working.
Also, would it be possible to have an option to hide the mouse cursor? (SDL_ShowCursor(SDL_DISABLE));

**Comment by gerstrong** [comment]
Do you mean as compile option or to be changed as User Setting? The ui is meant to be used with a mouse. If you have a mouse why not use it? So for rpi better always hide it? Or Auto hide?Am 01.01.2018 7:01 nachm. schrieb The Last Cabra <notifications@github.com>:Hi,
I have noticed the VIDEO->QUALITY setting (NEAREST/LINEAR) is not saved. It's a very simple problem, but it would be useful to have it working.
Also, would it be possible to have an option to hide the mouse cursor? (SDL_ShowCursor(SDL_DISABLE));

**Comment by vanfanel** [comment]
@gerstrong : I mean as an user setting. That way it would be always optional

**Comment by gerstrong** [comment]
Added ShowCursor option. This is for version 2.1 64bc7818

**Comment by vanfanel** [comment]
@gerstrong : Is release 2.1 near then? :)

**Comment by gerstrong** [comment]
yepAm 09.01.2018 5:05 nachm. schrieb The Last Cabra <notifications@github.com>:@gerstrong : Is release 2.1 near then? :)

**Comment by gerstrong** [comment]
fixed 46cd9909
