### ISSUE TITLE
Raspberry Pi Setup?

### ISSUE THREAD

**Issue by rokin4life7** [gerstrong/Commander-Genius#308]
I've copied git clone https://aur.archlinux.org/commander-genius-git.git into the terminal and I now see the commander genius folder in my home folder and there is a "PKGBuild" file in it.  It's automatically assigned as a text file.  How do I install the games or even get to a window in which I can?

**Comment by gerstrong** [comment]
Why are you using the AUR Repository? you need to execute makepkg on an arch system:

https://wiki.archlinux.de/title/Arch_User_Repository

**Comment by rokin4life7** [comment]
Forgive my ignorance.  I'm very new at the Raspberry Pi and how the terminal works
Can you give me a step by step of how to do this?

**Comment by rokin4life7** [comment]
I have the files downloaded but don't know how to install or run them.

**Comment by gerstrong** [comment]
You have to build it. That is Source Code you are dealing with... did you Check the README File?

**Comment by rokin4life7** [comment]
I'm not quite sure how to go about building it.  I've just never done that before.  I saw several readme files and that's why I'm reaching out.  I'm an engineer, but have only scratched the surface of software development and raspberry pi.  I need specific direction to get it done right and learn.

**Comment by gerstrong** [comment]
Hmm, not sure if this is the right for these kin d of questions. I do not even know what system you have installed on your pi. Have you tried on the pi forums? I recommend to get into debian for such devices.
