### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by ronilaukkarinen** [gerstrong/Commander-Genius#309]
I have RaspiBoy handheld device running retropie and I was wondering how to use SNES-like keypad (baked in) with Commander Genius? I have cgenius.cfg which is empty. In dosbox map file the keys are like this:

````
hand_shutdown "stick_0 button 9 mod3" "key 290 mod1"
hand_cycledown "key 292 mod1" "stick_0 button 6 mod3"
hand_cycleup "stick_0 button 7 mod3" "key 293 mod1"
hand_capmouse "key 291 mod1" 
hand_fullscr "key 13 mod2" 
hand_pause "key 19 mod2" 
hand_mapper "key 282 mod1" 
hand_speedlock "key 293 mod2" 
hand_recwave "key 287 mod1" 
hand_caprawmidi "key 289 mod1 mod2" 
hand_scrshot "key 286 mod1" 
hand_video "key 286 mod1 mod2" 
hand_decfskip "key 288 mod1" 
hand_incfskip "key 289 mod1" 
hand_caprawopl "key 288 mod1 mod2" 
hand_swapimg "key 285 mod1" 
key_esc "stick_0 button 5" "key 27" 
key_f1 "key 282" 
key_f2 "key 283" 
key_f3 "key 284" 
key_f4 "key 285" 
key_f5 "stick_0 button 4" "key 286" 
key_f6 "key 287" 
key_f7 "key 288" 
key_f8 "key 289" 
key_f9 "key 290" 
key_f10 "key 291" 
key_f11 "key 292" 
key_f12 "key 293" 
key_grave "key 96" 
key_1 "key 49" 
key_2 "key 50" 
key_3 "key 51" 
key_4 "key 52" 
key_5 "key 53" 
key_6 "key 54" 
key_7 "key 55" 
key_8 "key 56" 
key_9 "key 57" 
key_0 "key 48" 
key_minus "key 45" 
key_equals "key 61" 
key_bspace "key 8" 
key_tab "key 9" 
key_q "key 113" 
key_w "key 119" 
key_e "key 101" 
key_r "key 114" 
key_t "stick_0 button 3" "key 116" 
key_y "key 121" 
key_u "key 117" 
key_i "key 105" 
key_o "key 111" 
key_p "key 112" 
key_lbracket "key 91" 
key_rbracket "key 93" 
key_enter "stick_0 button 9" "key 13" 
key_capslock "key 301" 
key_a "key 97" 
key_s "key 115" 
key_d "key 100" 
key_f "key 102" 
key_g "key 103" 
key_h "key 104" 
key_j "key 106" 
key_k "key 107" 
key_l "key 108" 
key_semicolon "key 59" 
key_quote "key 39" 
key_backslash "key 92" 
key_lshift "stick_0 button 0" "key 304" 
key_lessthan "key 160" 
key_z "key 122" 
key_x "key 120" 
key_c "key 99" 
key_v "key 118" 
key_b "key 98" 
key_n "key 110" 
key_m "key 109" 
key_comma "key 44" 
key_period "key 46" 
key_slash "key 47" 
key_rshift "key 303" 
key_lctrl "key 306" 
key_lalt "stick_0 button 2" "key 308" 
key_space "stick_0 button 8" "key 32" 
key_ralt "key 307" 
key_rctrl "stick_0 button 1" "key 305" 
key_printscreen "key 316" 
key_scrolllock "key 302" 
key_pause "key 19" 
key_insert "key 277" 
key_home "key 278" 
key_pageup "key 280" 
key_delete "key 127" 
key_end "key 279" 
key_pagedown "key 281" 
key_up "stick_0 axis 1 0" "key 273" 
key_left "stick_0 axis 0 0" "key 276" 
key_down "stick_0 axis 1 1" "key 274" 
key_right "stick_0 axis 0 1" "key 275" 
key_numlock "key 300" 
key_kp_divide "key 267" 
key_kp_multiply "key 268" 
key_kp_minus "key 269" 
key_kp_7 "key 263" 
key_kp_8 "key 264" 
key_kp_9 "key 265" 
key_kp_plus "key 270" 
key_kp_4 "key 260" 
key_kp_5 "key 261" 
key_kp_6 "key 262" 
key_kp_1 "key 257" 
key_kp_2 "key 258" 
key_kp_3 "key 259" 
key_kp_enter "key 271" 
key_kp_0 "key 256" 
key_kp_period "key 266" 
jbutton_0_0 "stick_0 button 0" 
jbutton_0_1 "stick_0 button 1" 
jaxis_0_1- "stick_0 axis 1 0" 
jaxis_0_1+ "stick_0 axis 1 1" 
jaxis_0_0- "stick_0 axis 0 0" 
jaxis_0_0+ "stick_0 axis 0 1" 
jbutton_0_2 "stick_0 button 2" 
jbutton_0_3 "stick_0 button 3" 
jbutton_1_0 
jbutton_1_1 
jaxis_0_2- "stick_0 axis 2 0" 
jaxis_0_2+ "stick_0 axis 2 1" 
jaxis_0_3- "stick_0 axis 3 0" 
jaxis_0_3+ "stick_0 axis 3 1" 
jaxis_1_0- 
jaxis_1_0+ 
jaxis_1_1- 
jaxis_1_1+ 
jbutton_0_4 "stick_0 button 4" 
jbutton_0_5 "stick_0 button 5" 
jhat_0_0_0 "stick_0 hat 0 1" 
jhat_0_0_3 "stick_0 hat 0 8" 
jhat_0_0_2 "stick_0 hat 0 4" 
jhat_0_0_1 "stick_0 hat 0 2" 
mod_1 "key 306" "key 305" 
mod_2 "key 308" "key 307" 
mod_3 
````

How to make the same keys work with cgenius? thanks in advance.

**Comment by gerstrong** [comment]
The cgenius.cfg is modified automatically as soon as you start the game and configure your controls. I would connect a keyboard or mouse to your device, start one of the games, go into Settings->controls->Player 1 and from there to "Movement" and "Buttons". Now you can map the controls of your dpad and the buttons. After you have finished that you can disconnect your mouse and/or keyboard because all the menus are also joystick driven. When you quit the game you will have a cgenius.cfg with the mapped joypad assignments which you can copy wherever you want. I have a Logitech F30 for my tests. I can send you my cfg for that later if you want but I think the mapping is a bit different than in your case. You can easily hack those files also, very simple in fact...

**Comment by ronilaukkarinen** [comment]
Oh, okay! that explains it. I currently cannot control Commander Genius at all because can't select the game. I have configured DOSBox on my macbook, mapped the keys, then copied mapfile to my handheld device. I think in this case I need to do the same, because for some reason my device doesn't recognize normal keyboard. You could send your cfg, I could try to hack it OR do it on my mac as I previously described.

**Comment by gerstrong** [comment]
here you go:

````
[Audio]
channels = 2
format = 32784
musicvol = 16
rate = 44100
sndblaster = false
soundvol = 16

[Bound]
down = 130
left = 140
right = 180
speed = 5
up = 50

[FileHandling]
SearchPath1 = ${HOME}/.CommanderGenius
SearchPath2 = .
SearchPath3 = /usr/share/games/commandergenius

[Game]
hud = true
keystack = false
level_replayability = false
modern_style = true
pking = true
rise_bonus = true
showfps = false
specialfx = true

[Video]
OGLfilter = nearest
OpenGL = true
VirtPad = false
aspect = 4:3
filter = 1
fps = 60
fullscreen = false
gameHeight = 200
gameWidth = 320
height = 600
scale = 1
scaletype = normal
vsync = true
width = 800

[input0]
Analog = false
Back = Joy0-B6
Camlead = Joy0-B8
Down = Joy0-A1+
Fire = Joy0-B1
Help = Joy0-B9
Jump = Joy0-B0
Left = Joy0-A0-
Lower-Left = Key 1073741901 (End)
Lower-Right = Key 1073741902 (PageDown)
Pogo = Joy0-B3
Right = Joy0-A0+
Run = Joy0-B2
Status = Joy0-B7
TwoButtonFiring = false
Up = Joy0-A1-
Upper-Left = Key 1073741898 (Home)
Upper-Right = Key 1073741899 (PageUp)

[input1]
Analog = false
Back = Key 27 (Escape)
Camlead = Key 99 (C)
Down = Key 1073741905 (Down)
Fire = Key 32 (Space)
Help = Key 1073741882 (F1)
Jump = Key 1073742048 (Left Ctrl)
Left = Key 1073741904 (Left)
Lower-Left = Key 1073741901 (End)
Lower-Right = Key 1073741902 (PageDown)
Pogo = Key 1073742050 (Left Alt)
Right = Key 1073741903 (Right)
Run = Key 1073742049 (Left Shift)
Status = Key 13 (Return)
TwoButtonFiring = false
Up = Key 1073741906 (Up)
Upper-Left = Key 1073741898 (Home)
Upper-Right = Key 1073741899 (PageUp)

[input2]
Analog = false
Back = Key 27 (Escape)
Camlead = Key 99 (C)
Down = Key 1073741905 (Down)
Fire = Key 32 (Space)
Help = Key 1073741882 (F1)
Jump = Key 1073742048 (Left Ctrl)
Left = Key 1073741904 (Left)
Lower-Left = Key 1073741901 (End)
Lower-Right = Key 1073741902 (PageDown)
Pogo = Key 1073742050 (Left Alt)
Right = Key 1073741903 (Right)
Run = Key 1073742049 (Left Shift)
Status = Key 13 (Return)
TwoButtonFiring = false
Up = Key 1073741906 (Up)
Upper-Left = Key 1073741898 (Home)
Upper-Right = Key 1073741899 (PageUp)

[input3]
Analog = false
Back = Key 27 (Escape)
Camlead = Key 99 (C)
Down = Key 1073741905 (Down)
Fire = Key 32 (Space)
Help = Key 1073741882 (F1)
Jump = Key 1073742048 (Left Ctrl)
Left = Key 1073741904 (Left)
Lower-Left = Key 1073741901 (End)
Lower-Right = Key 1073741902 (PageDown)
Pogo = Key 1073742050 (Left Alt)
Right = Key 1073741903 (Right)
Run = Key 1073742049 (Left Shift)
Status = Key 13 (Return)
TwoButtonFiring = false
Up = Key 1073741906 (Up)
Upper-Left = Key 1073741898 (Home)
Upper-Right = Key 1073741899 (PageUp)
````

**Comment by ronilaukkarinen** [comment]
I got it working perfectly with controls and movement, but cannot save game, since I don't have any letters to type and it seems not to save empty slot. Any tips? or can I map some letter for example to one of the keys somehow?

**Comment by ronilaukkarinen** [comment]
I can see the saves in files (cksave1.cx1) but all is empty when going to Load menu. If there's no way to map a key to one of the buttons, I guess I can edit the file and add the save name there via SSH, but where to add it?

**Comment by gerstrong** [comment]
Hi, you have to compile it differently. Not sure how the Switch was called but enabling it will build CG the way it automatically puts date and time as name. We use this for Android Ports also. Let me check this...Am 16.01.2018 4:46 nachm. schrieb Roni Laukkarinen <notifications@github.com>:I got it working perfectly with controls and movement, but cannot save game, since I don't have any letters to type and it seems not to save empty slot. Any tips? or can I map some letter for example to one of the keys somehow?

**Comment by gerstrong** [comment]
okay, try to get the latest master branch. Now using cmake, set enable option NOTYPESAVE from the cmake-gui or with -DNOTYPESAVE=on if using CLI. Let it build. Now it should produce a binary where you won't need to type.

**Comment by ronilaukkarinen** [comment]
Thank you very much! as I use retropie, I had to edit option to `/home/pi/RetroPie-Setup/scriptmodules/ports/cgenius.sh`, obviously. Building now in 8%. Last time it took many hours since RaspiBoy works on Raspberry Pi Zero, but it's well worth the wait.

**Comment by ronilaukkarinen** [comment]
In case any googler is wondering how I solved the gamepad issue on RaspiBoy, I figured out it this way: installed macOS version of Commander Genius, plugged in my second keypad (which has the same mappings than on the handheld), started keen1 with my keyboard, then configured the buttons. Searched for cgenius.cfg in Application Support, opened it, copy pasted the input sections to my raspberry pi and voilà!

**Comment by ildar** [comment]
Maybe it's a good idea to bring default configs with binary packages or
even in the source tree. @gerstrong ?

**Comment by gerstrong** [comment]
The defaults are hard coded and depend on how CG is being built. CG can live without a configuration file if necessary. You can bundle one in your setups if you want so... I am not yet fully convinced to include one. On the other hand it easily could be altered... CG generates one after the first run anyways...Am 17.01.2018 1:11 vorm. schrieb ildar <notifications@github.com>:Maybe it's a good idea to bring default configs with binary packages or
even in the source tree. @gerstrong ?

**Comment by ronilaukkarinen** [comment]
Thank you @gerstrong! Confirmed working after recompile. See for yourself:

![RaspiBoy](https://i.imgur.com/3V015oA.jpg "RaspiBoy")

**Comment by gerstrong** [comment]
Very cool ☺️

**Comment by gerstrong** [comment]
Can I post your picture on our Website? I would like to show more stuff of what others did with Commander Genius.

**Comment by ronilaukkarinen** [comment]
Of course!

**Comment by bigblockentmt** [comment]
Looking for anyone that can help Install Commander Genius or Commander Keen on the SUMOSYS.

SUMO is using Recalbox system.

I do have DOSBOX but I can never get it to Mount or play
