### ISSUE TITLE
no sound on keen1, and keentfos crash on load (win 10 64)

### ISSUE THREAD

**Issue by necros2k7** [gerstrong/Commander-Genius#312]
subj

**Comment by gerstrong** [comment]
Yes, SDL_Mixer will be used in the next release and resolve that problem. KeenTFOS is not really that good supported. But don't worry I also am working on that.

**Comment by gerstrong** [comment]
Added SDL_mixer. The situation should be much improved. On TFOS I will take a look later...

**Comment by necros2k7** [comment]
still crash with new ver after starting KEEN5 ver1 game ( P.S. why not use sdl2_mixer on newer ver 2.1.2?

**Comment by gerstrong** [comment]
Nope. Please use Keen 5 ver 1.4. You can check the supported versions in the readme file. I am distributing SDL_mixer 2.0.2 which is the latest. Please check your dlls

**Comment by necros2k7** [comment]
OK, but I meant why not use sdl_mixer with CommanderGenius 2.1.2? (i`m not talking about dll ver)

**Comment by gerstrong** [comment]
For that there is 2.1.5Am 03.02.2018 3:14 vorm. schrieb necros2k7 <notifications@github.com>:OK, but I meant why not use sdl_mixer with CommanderGenius 2.1.2? (i`m not talking about dll ver)
