### ISSUE TITLE
Video options crash Keen 1

### ISSUE THREAD

**Issue by levinnd** [gerstrong/Commander-Genius#313]
On the Keen 1 menu, if I hit configure and then hit video, Commander Genius crashes. This is on Android, v 1.9.9.8-beta. Also, when does 2.0 come out for Android? I'm really excited for it.

**Comment by gerstrong** [comment]
I know. I need to update this one. Will do when other problem with CG especially on Windows are solved.

**Comment by gerstrong** [comment]
Just uploaded CG Version 2.0 for Android.
