### ISSUE TITLE
Insanely distorted sound, crackly, gets loud until ear-rape.

### ISSUE THREAD

**Issue by StrikerMan780** [gerstrong/Commander-Genius#314]
Seems in the latest build on PC, the sound in CG is extremely distorted, none of the adlib/soundblaster sounds come out right, and the sound gets louder and louder until it becomes absolutely deafening. I am not sure why. I've attempted to change sample rates, go to mono... nothing works.

Running on Windows 10 x64.

**Comment by gerstrong** [comment]
Alright, let me take on this. Actually I'm trying to get SDL_Mixer into this, so not only the bugs will be fixed, more formats will be supported.

**Comment by gerstrong** [comment]
Alright. I had some time to check SDL_mixer and add it to Commander Genius. The sound really has improved. Let me refine some aspects and newer release will solve your problem.

I will close this, when ready. Please let me know then, if the bug has gone away then.

**Comment by gerstrong** [comment]
Okay, got you covered with SDL_Mixer this time. Try out version 2.0.5

**Comment by StrikerMan780** [comment]
Alright, thanks. I'll give it a shot.

**Comment by StrikerMan780** [comment]
OK. First run = Music OK with Keen4plus, but crackly. No adlib sounds... Went the sound menu, changed sample rate, became an extremely loud, distorted ear-piercing mess again, went back into sound configuration menu, pressed escape, ear-destroying music stops, no music at all, adlib sounds work.

**Comment by StrikerMan780** [comment]
Definitely not PC Speaker sound. I mean crackly as if it's buffer underrunning. Ie, snaps and pops.

**Comment by gerstrong** [comment]
Oh okay. Schall we increase the buffer then. Might that Help?Am 03.02.2018 9:28 nachm. schrieb Jordon Moss <notifications@github.com>:Definitely not PC Speaker sound. I mean crackly as if it's buffer underrunning. Ie, snaps and pops.

**Comment by georgbachmann** [comment]
I am currently facing the same problem on my RaspberryPi where Commander-Genius is run as part of RetroPie. I managed to get everything working, but sound is off. With other games it's working fine.
I have about zero knowledge about Linux and Sound though... so any help would be greatly appreciated!!!
Cheers,
