### ISSUE TITLE
cannot build from retropie

### ISSUE THREAD

**Issue by djfurypants** [gerstrong/Commander-Genius#315]
Youll have to forgive me because i am very new to this but i tired to install cgenius from experimental packages and am being told it could not successfully install because cgenius/src/CGeniusEXe was not found.  Any help would be appreciated, these games mean a lot to me

**Comment by gerstrong** [comment]
Hmm, any log would be helpful. How did it try to compile?

**Comment by djfurypants** [comment]
I just installed it from the experimental packages menu I'm not sure on how it compiled. As for a log I will gladly share one with a little direction on how and where to make one

**Comment by gerstrong** [comment]
Pretty sure there is a way. Am 01.02.2018 11:23 nachm. schrieb djfurypants <notifications@github.com>:I just installed it from the experimental packages menu I'm not sure on how it compiled. As for a log I will gladly share one with a little direction on how and where to make one

**Comment by gerstrong** [comment]
I have pushed an Update. On my tests CG runs fine using retropie.

**Comment by djfurypants** [comment]
Glad it works for someone. I'm using a pi 3

**Comment by gerstrong** [comment]
Can you test my fork? I have no rpi 3 right now at my hands...

**Comment by djfurypants** [comment]
I can try. Is there any detailed info I need to know for the install as following your directions in your readme didn't seem to work as it would not build

**Comment by gerstrong** [comment]
Not really, cmake for the build directory, make in the directory and make install for system installation. Just ensure all the dependencies are installed and use the v2.2.0 tag for best stability. That one is configured in my fork of Retropie.
