### ISSUE TITLE
Downloading tags is broken due to submodules / create releases

### ISSUE THREAD

**Issue by hasufell** [gerstrong/Commander-Genius#316]
Submodules break github tags.

```
CMake Error at CMakeLists.txt:56 (MESSAGE):
  You need to have the sources of GsKit in order to build Commander Genius.
  If you got the sources from github try to this in the source directory: git
  submodule init &&git submodule update
```

A solution is to upload [proper releases](https://help.github.com/articles/creating-releases/) by using `git archive`.

**Comment by gerstrong** [comment]
Ahh yes, need to review that method. It might be better instead of using tags...

**Comment by hasufell** [comment]
Still an issue, cannot package

**Comment by gerstrong** [comment]
After some cleanups and through many annoyances I put GsKit back to CG. It should build now without any problems.

**Comment by hasufell** [comment]
Thanks.

I noticed that you removed **tags**. That can break distro packages that rely on older versions (e.g.: https://github.com/hasufell/hasufell-repository/tree/master/packages/games-arcade/Commander-Genius). I would suggest to not remove tags.

**Comment by gerstrong** [comment]
Thanks for the hint. Cleaning up was a bit radical this time, I know for sure, but the last tag I created really has the best code so far. I think the few distros supporting will take that one. On the other hand there still is the Archive repo...

**Comment by gerstrong** [comment]
I won't clean up so radically in Future...
