### ISSUE TITLE
Black boxes around sprites

### ISSUE THREAD

**Issue by djfurypants** [gerstrong/Commander-Genius#317]
I figured out how to install it but now I have a new issue black boxes around all sprites(keen1-3 keen 4-6 the boxes are light blue). Probably something simple but I can't find anything that'll get rid of them

**Comment by djfurypants** [comment]
![20180203_120901](https://user-images.githubusercontent.com/36023481/35770290-067cd25c-08de-11e8-97b2-d4cee2cc0148.jpg)
![20180203_120913](https://user-images.githubusercontent.com/36023481/35770291-06986ca6-08de-11e8-8e89-a32d4b9a0d20.jpg)
![20180203_120926](https://user-images.githubusercontent.com/36023481/35770292-06b26368-08de-11e8-8222-4a738ededd47.jpg)

**Comment by gerstrong** [comment]
Did you compile it? How did you build? Which version are you using? Which SDL? This is clearly an alpha and color key issue.

**Comment by djfurypants** [comment]
i believe its 1.8 whatever is in the retropie exp packages. this is about all i know how to offer you so i hope this contains what you need to help me
[rps_2018-02-03_051308.log](https://github.com/gerstrong/Commander-Genius/files/1692148/rps_2018-02-03_051308.log)

**Comment by gerstrong** [comment]
Ahh alright. This Log helps a lot. Not sure why it happens, but we need to Update this to Version 2.0. gfx got an overhaul, so let's so that...Am 03.02.2018 9:05 nachm. schrieb djfurypants <notifications@github.com>:i believe its 1.8 whatever is in the retropie exp packages. this is about all i know how to offer you so i hope this contains what you need to help me
rps_2018-02-03_051308.log

**Comment by djfurypants** [comment]
You are going to update the source from retropie or do I need to install the update by other means?

**Comment by gerstrong** [comment]
I have sent a merge request. Let's hope the main devs take so you get the update. Otherwise you will have to use my retropie fork. Hope it fixes you problem also...

**Comment by djfurypants** [comment]
Well I think after 9 days of no new update, I think I'm ready for your retropie fork.  Thank you for all your help

**Comment by gerstrong** [comment]
Good, let me know if it is better this time...

**Comment by djfurypants** [comment]
Having issues with the make command im trying to see if I have a log to show you

**Comment by gerstrong** [comment]
Yes, please... :-)

**Comment by djfurypants** [comment]
Still broken I just hit a wall, it won't build and I can find where it's logging if it is at all

**Comment by gerstrong** [comment]
I have send a more recent version for retropie. I tested that one and didn't get any problems. It built fine and no black boxes. What device are you using? You might have a lower depth in terms of resolution.
