### ISSUE TITLE
Cgenius crashes when you enter a keen 4 level

### ISSUE THREAD

**Issue by levinnd** [gerstrong/Commander-Genius#318]
This is on the new android release that just went out.

**Comment by gerstrong** [comment]
Yeah, the android version had a strange behavior with the Music player. It should be better with the fix I uploaded.

**Comment by levinnd** [comment]
It no longer crashes, I can enter a level. However, it no longer plays music.

**Comment by Thilo1** [comment]
I am still having this issue. App crashes when loading a keen4 saved Game. Nexus 5x oreo

**Comment by Thilo1** [comment]
I pulled an update from the Play Store. IT appears to be fixed, the Version says still 2.0.7 release Like before though. I thought the Apps were updating automatically.

**Comment by gerstrong** [comment]
Many issues are crashes now. Please ensure you really have the very latest version of Cgenius. I uploaded another one some hours ago. If that is the case, I might need some more Information and maybe even your data. I have a Nexus 6 and everything runs fine here now...So I think it is related to your setup...Am 13.02.2018 6:48 vorm. schrieb Thilo1 <notifications@github.com>:I am still having this issue. App crashes when loading a keen4 saved Game. Nexus 5x oreo

**Comment by gerstrong** [comment]
I should have changed the number. Google Play Store is a bit strange in Updates sometimes. Some hours ago I was working hard fixing many Sdl Mixer Integration issues that still were left. Now it should be much better... ☺Am 13.02.2018 7:05 vorm. schrieb Thilo1 <notifications@github.com>:I pulled an update from the Play Store. IT appears to be fixed, the Version says still 2.0.7 release Like before though. I thought the Apps were updating automatically.

**Comment by Thilo1** [comment]
Ok, appears to be fixed. There is a typo in the Version String. "2.0.7 Relase"

**Comment by levinnd** [comment]
All the keen 4 issues appear fixed for me. I do hear a squish like sound the first time Keen moves when I start the game, but that doesn't bother me.

**Comment by gerstrong** [comment]
okay, good. Not sure why you hear that, but I might discover what it is. I will close this track then...
