### ISSUE TITLE
Cgenius crashes upon entering keen 6 level

### ISSUE THREAD

**Issue by levinnd** [gerstrong/Commander-Genius#320]
Like with keen 4, Cgenius crashes when you enter a keen 6 level. Mysteriously, its fine when you enter a keen 5 level. This is on android.

**Comment by gerstrong** [comment]
Found some issues, fixed them. Let me know if it is better with the update I transferred right now.

**Comment by levinnd** [comment]
It no longer crashes, however, it also no longer plays music.

**Comment by gerstrong** [comment]
I have uploaded Version 2.0.7 on tested that one Windows 10. The crash does not happens anymore...

**Comment by levinnd** [comment]
I can confirm that it works on my phone.
