### ISSUE TITLE
CGenius crashes when I load a save on Keen 4 Plus

### ISSUE THREAD

**Issue by Makedonecc** [gerstrong/Commander-Genius#321]
Whenever I try to load my save game when playing Keen 4 Plus, it crashes and gives me a Runtime Error, saying that the application requested the runtime to terminate it in an unusual way.

**Comment by gerstrong** [comment]
Are we talking about Windows Here ?Am 04.02.2018 8:08 nachm. schrieb Makedonecc <notifications@github.com>:Whenever I try to load my save game when playing Keen 4 Plus, it crashes and gives me a Runtime Error, saying that the application requested the runtime to terminate it in an unusual way.

**Comment by Makedonecc** [comment]
Yes. Windows 10 to be specific.

**Comment by gerstrong** [comment]
I have uploaded Version 2.0.7 on tested that one Windows 10. The crash does not happens anymore...
