### ISSUE TITLE
Cgenius crashes upon exiting keen 4 level.

### ISSUE THREAD

**Issue by levinnd** [gerstrong/Commander-Genius#323]
This is on android.

**Comment by gerstrong** [comment]
can you let me know which device you have. My android is not affected but I will try to test your constellation on an emulator.

**Comment by levinnd** [comment]
It's an S8G Galaxy Plus. I just got it ~ October 2017.

**Comment by gerstrong** [comment]
I have uploaded Version 2.0.7 on tested that one Windows 10. The crash does not happens anymore...

**Comment by levinnd** [comment]
I can confirm that it works on my phone.
