### ISSUE TITLE
Android unplayable

### ISSUE THREAD

**Issue by hurleybird** [gerstrong/Commander-Genius#325]
Can't start a new game on any Keen game (1-6). Sometimes music will play after going through the steps to start a game. Can exit the menu with the X button to the right and see the game, but get kicked back to the menu a moment later.

**Comment by gerstrong** [comment]
I have fixed a lot of thing for android lately. Closing this. Please reopen if you still have the issues

**Comment by hurleybird** [comment]
Don't think I have permissions to reopen but yes, it's still totally broken for me.
