### ISSUE TITLE
Keen 3 Version 1.31

### ISSUE THREAD

**Issue by Thilo1** [gerstrong/Commander-Genius#330]
In the final Boss Level, when Keen fights against the mangling machine, i can't shoot out all the purple spots/lights. I can shoot most of the times six lights out, the seventh remains lit, regardless how many times i hit it with the blaster.

**Comment by gerstrong** [comment]
Can you shoot at the heart? That would the Last spot for killing the Machine...Am 21.02.2018 8:14 nachm. schrieb Thilo1 <notifications@github.com>:In the final Boss Level, when Keen fights against the mangling machine, i can't shoot out all the purple spots/lights. I can shoot most of the times six lights out, the seventh remains lit, regardless how many times i hit it with the blaster.

**Comment by Thilo1** [comment]
It's not possible, the arms don't fall off. Sometimes more than one of the purple spots don't disappear when being hit

**Comment by gerstrong** [comment]
Sorry, I cannot confirm that after my tests. Maybe the next upcoming (2.2.0) update solves the problem. Stay tuned..
