### ISSUE TITLE
Possible incompatible GPL/OSI licensing found

### ISSUE THREAD

**Issue by jengelh** [gerstrong/Commander-Genius#333]
Wanting to put the Commander Genius into the openSUSE Linux distribution, I had a cursory look at licensing, and found what looks to me like an OSI-incompatible clause in `src/fileio/crc.cpp`:

```
// This code is copyright © 1993 Richard Black. All rights are reserved. You
// may use this code only if it includes a statement to that effect.
```

The file lacks such a statement, which means that code cannot be "used". In addition, this license does not grant any rights for the usual other freedoms including, but not limited to, "modify" and "distribute". This, I figure, currently prevents inclusion into most such libre software distributions.
It would be really great if this issue could be resolved. Thank you.

**Comment by gerstrong** [comment]
hi, thanks for noting. I had no idea about this. CRC is something we can probably remove or replace by something else.

**Comment by gerstrong** [comment]
Let me know if you find something else. Seeing this in openSUSE Linux would be great :-)

**Comment by gerstrong** [comment]
I think we can close this. GsKit is not a submodule anymore anyways..

**Comment by jengelh** [comment]
Eh this ticket was not about GsKit, it was about crc.cpp.

**Comment by gerstrong** [comment]
Right, thanks. I have removed the CRC files also, they were not used anymore...
