### ISSUE TITLE
Almost all files have +x permissions

### ISSUE THREAD

**Issue by jengelh** [gerstrong/Commander-Genius#334]
It is kinda wrong to have all files with +x in the repository. Resetting master also wasn't such a great idea :-/

**Comment by gerstrong** [comment]
It is yes, have to fix that also. The repo is smaller and the code builds fine. I did not use git init for this...

I also created Commander-Genius-Archive but might have the same mentioned issues.

**Comment by gerstrong** [comment]
here we go 7255f0c6
