### ISSUE TITLE
Keen 4 Plus crashes when loading savegame

### ISSUE THREAD

**Issue by lavolp3** [gerstrong/Commander-Genius#337]
Keen 4 Plus crashes when I try to load a recently saved game.
Tried it in retropie 4.4 on a Raspberry Pi 3, then it crashed back to the emulationstation menue without any message.
Also tried in Windows 10 64 bit environment (Keen 4 Plus v. 1.4), then it crashed with a runtime error.

**Comment by gerstrong** [comment]
I find that a bit strange. Which CG Version are you using? Retropie should have the latest one.

Can you send me that savefile? I would like to perform some Tests.

**Comment by lavolp3** [comment]
[cksave3.zip](https://github.com/gerstrong/Commander-Genius/files/1914302/cksave3.zip)

On windows I have downlaoded the 2.2.0 as zip and just started that.
The save is stored under "..Documents\Commander Genius\save\games\Keen 4 Plus\Keen4Plus"

**Comment by gerstrong** [comment]
Okay thanks will check that later. Thanks for sharing.

**Comment by lavolp3** [comment]
Here is the save from retropie. Same problem. Don't know what I'm doing wrong...

[cksave1-retropi.zip](https://github.com/gerstrong/Commander-Genius/files/1916903/cksave1-retropi.zip)

**Comment by gerstrong** [comment]
Tested on my system, so far these two file both open just fine. I Will test on it another system in a while -> Windows and Retropie

Must set those up. I have a new system here...

**Comment by gerstrong** [comment]
Confirmed. On Windows 10 it does crash. I think it is the same problem as on RPi. I'm going to have this fixed for the next release.

**Comment by gerstrong** [comment]
Okay, tested against latest version 2.2.1 and does not crash anymore. Try it out and reopen this ticket if you still have problem.

I have created a merge request for Retropie. If you can't wait you can use my repo for the meanwhile.

**Comment by lavolp3** [comment]
Thanks!
But Now I can't start it on Win 10 64 bit. "SCL2_mixer.dll not found."
Tried the zip package and the installer. Both with the same result...

**Comment by gerstrong** [comment]
My mistake, forgot to bundle that DLL. You can get it here: https://www.libsdl.org/projects/SDL_mixer/

Take the runtime x86 package and extract it where the exe is. I will bundle it for next release.
