### ISSUE TITLE
Keen 4 Plus Perilous Pit Ending

### ISSUE THREAD

**Issue by lavolp3** [gerstrong/Commander-Genius#338]
In Keen 4 Plus V 1.4, downloaded from CGenius Menu, in Perilous Pit (the level by the water), the level is not ending after meeting the druid/wise one. I think it should. I see no other way to end the level.
Using Win 10 and CGenius 2.2.1

**Comment by gerstrong** [comment]
You are right. Happened with this last release. Look out for v2.2.2. It also has options in the Launcher.
