### ISSUE TITLE
/home/pi/Commander-Genius/src/engine/keen/galaxy/common/ai/platform/CVarPlatform.h:33:10: internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by nibio74** [gerstrong/Commander-Genius#341]
Around 41% of the compilation this error appears:

In file included from /home/pi/Commander-Genius/src/engine/keen/galaxy/common/ai/platform/CVarPlatform.cpp:8:0:
/home/pi/Commander-Genius/src/engine/keen/galaxy/common/ai/platform/CVarPlatform.h: In member function ‘virtual void galaxy::CVarPlatform::_ZTv0_n120_N6galaxy12CVarPlatform9serializeER19CSaveGameController(CSaveGameController&)’:
/home/pi/Commander-Genius/src/engine/keen/galaxy/common/ai/platform/CVarPlatform.h:33:10: internal compiler error: Segmentation fault
void serialize(CSaveGameController &savedGame);
^
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.9/README.Bugs for instructions.
Preprocessed source stored into /tmp/ccA5tslK.out file, please attach this to your bugreport.
src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/build.make:638: recipe for target 'src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/ai/platform/CVarPlatform.cpp.o' failed
make[2]: *** [src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/ai/platform/CVarPlatform.cpp.o] Error 1
CMakeFiles/Makefile2:859: recipe for target 'src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/all' failed
make[1]: *** [src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
[ccA5tslK.out.txt](https://github.com/gerstrong/Commander-Genius/files/1982116/ccA5tslK.out.txt)

**Comment by gerstrong** [comment]
Why is this version bundled anyways? To my knowledge there already exists version 8.0. Even mingw packages of qt provide 5.3 which is old but is fine for CG sources. (I use that one for the Windows builds and it never fails)

**Comment by nibio74** [comment]
I do not know why it's so old, I compiled it with the gcc I found in retropies. Is there a way to update that and try again to recompile Commander Genius?

**Comment by nibio74** [comment]
I try now, I'll update you. Thanks.

**Comment by nibio74** [comment]
Unfortunately it did not work. The same error was found:

In file included from /home/pi/Commander-Genius/src/engine/keen/galaxy/common/ai/platform/CVarPlatform.cpp:8:0:
/home/pi/Commander-Genius/src/engine/keen/galaxy/common/ai/platform/CVarPlatform.h: In member function ‘virtual void galaxy::CVarPlatform::_ZTv0_n120_N6galaxy12CVarPlatform9serializeER19CSaveGameController(CSaveGameController&)’:
/home/pi/Commander-Genius/src/engine/keen/galaxy/common/ai/platform/CVarPlatform.h:32:10: internal compiler error: Segmentation fault
     void serialize(CSaveGameController &savedGame);
          ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Preprocessed source stored into /tmp/ccHKfQqH.out file, please attach this to your bugreport.
src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/build.make:638: recipe for target 'src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/ai/platform/CVarPlatform.cpp.o' failed
make[2]: *** [src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/ai/platform/CVarPlatform.cpp.o] Error 1
CMakeFiles/Makefile2:859: recipe for target 'src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/all' failed
make[1]: *** [src/engine/keen/galaxy/common/CMakeFiles/engine_keen_galaxy_common.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
[ccHKfQqH.out.txt](https://github.com/gerstrong/Commander-Genius/files/1994238/ccHKfQqH.out.txt)

**Comment by gerstrong** [comment]
I can see in the error that it really is the new code. Too bad. It helped a bit on performance but the crash is still there :-( 

I see no other way than updating the compiler somehow. Let me see what we can do and get back to you.

**Comment by gerstrong** [comment]
On what system are you building this anyways. OS, Distro version?

**Comment by gerstrong** [comment]
Forget the question, the log says it...
But still, is retropie stretch not based on debian stretch? Stretch uses version 6.3. This makes me wonder a lot.

Did you perform any retropie upgrade from an older version?

**Comment by nibio74** [comment]
Yes, I upgraded from retropie 4.3 to retropies 4.4. Do I have to try with a clean distro starting from the retropie 4.4?

**Comment by ildar** [comment]
I'm not sure about upgrade procedure of Retropie / underlying Raspbian but
it may be that gcc wasn't upgraded. Plz check with the community.
-- 
Ildar Mulyukov,
(ΙΧΘΥΣ) child of God

email: ildar.mulyukov@gmail.com
matrix: @ildar:matrix.org
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by gerstrong** [comment]
@nibio74 I think you are not fully upgraded to retropie 4.4
My fresh installation on a RPi reports gcc version 6.3.

I tried it on a real Raspberry Pi this time and everything works as expected. The compilation time takes a bit of time but succeeds...

Not sure if something like do-release-update (Ubuntu) exists. Maybe a fresh installation is better for you, I cannot tell.
