### ISSUE TITLE
Not installable on Ubuntu 18.04

### ISSUE THREAD

**Issue by mdebusk** [gerstrong/Commander-Genius#342]
Not only is there no "bionic" PPA, but when attempting to install from the "zesty" ppa, the following error message is received:
```
The following packages have unmet dependencies:
   commandergenius : Depends: libcurl3 (>= 7.16.2) but it is not going to be installed
   Depends: libpython3.5 (>= 3.5.0~b1) but it is not installable
```

**Comment by ildar** [comment]
IMHO you should open the issue at the Launchpad, not here

**Comment by mdebusk** [comment]
I would if there was an obvious way to do that.

**Comment by gerstrong** [comment]
Yeah, the PPA needs an update. You can still compile it yourself...

**Comment by gerstrong** [comment]
I think 18.04 uses Python 3.6 upwards. No prob for CG but the PPA is a bit old.

**Comment by gerstrong** [comment]
Okay, I sent an update to the PPA. I have to wait now, so it gets confirmed. After that you will have CG 2.2.3ppa1 (from the current stable) installable from there.

**Comment by mdebusk** [comment]
Thanks so much! I had upgraded to Bionic and was missing Commander Keen. :)

**Comment by gerstrong** [comment]
We got update for bionic beaver in my PPA! Check it out!

**Comment by mdebusk** [comment]
It's alive! Thank you so much. :)
