### ISSUE TITLE
Invisible platforms on android (2.0.7)

### ISSUE THREAD

**Issue by innuendo1231** [gerstrong/Commander-Genius#345]
Hello devs!
I'm using the latest available android version (2.0.7).
In Keen 6, some of the yellow floating platforms seem to be invisible. At first I though they were missing, but then I realized that they are there, but they are invisible. So far I noticed two cases: 
Level one, the platform that would take you to the queen viva. 
First Dome of Darkness, the platform that would take you to the blue gem.
These are both moving platforms activated by switches.

**Comment by gerstrong** [comment]
Hi, I have removed the repo to gitlab, please discussing there. 

I will take a look and fix it.
