### ISSUE TITLE
Retropie 4.4.4 build failed, CGeniusExe missing?

### ISSUE THREAD

**Issue by hhhmmm2019** [gerstrong/Commander-Genius#346]
Hello,
I tried to build Commander Genius on new retropie 4.4.4. (rPi3B+) with the included **cgenius** script in Retropie setup.
It is not working: /home/pi/RetroPie-Setup/tmp/build/cgenius/src/cGeniusExe not found

Attached are 3 logs:
[CMakeError.log](https://github.com/gerstrong/Commander-Genius/files/2719620/CMakeError.log)
[CMakeOutput.log](https://github.com/gerstrong/Commander-Genius/files/2719621/CMakeOutput.log)
[rps_2019-01-01_212734.log](https://github.com/gerstrong/Commander-Genius/files/2719622/rps_2019-01-01_212734.log)

As I am a total newbie to linux, I'd really appreciate some idea or help.

Thanks!

**Comment by gerstrong** [comment]
Python and Boost have become optional. Do you still have problems?

**Comment by gerstrong** [comment]
Check out the latest master. Issues should be gone.
