### ISSUE TITLE
[Feature] option to turn off "achievements" when you play (v2.6.3.1)

### ISSUE THREAD

**Issue by arrowgent** [gerstrong/Commander-Genius#361]
i get why people love achievements
but having a large box on the screen for 5-10 seconds is also an annoyance

can you add an option to disable the pseudo-achievements?

thanks!  love your work with this port

**Comment by gerstrong** [comment]
Hi @arrowgent ,
sorry for the late answer. This ticket somehow got lost.

I have added feature in version 3.1.2. Hope you enjoy it.

BR
Gerhard
