### ISSUE TITLE
[bug] search ignores cfg option for search directories (v2.6.3.1) - Linux

### ISSUE THREAD

**Issue by arrowgent** [gerstrong/Commander-Genius#362]
set path in ~/.CommanderGenus/cgenius.cfg
```
[FileHandling]
SearchPath1 = ${HOME}/.CommanderGenius
SearchPath2 = ${HOME}/.CommanderGenius
SearchPath3 = ${HOME}/.CommanderGenius
```
but the binary still searches other directories for games:
```
n: Search on vfs: games/doom

n: Scanning ./games/dosbox/blood/setup.exe 
n: Scanning ./games/dosbox/blood/unstall.exe 

n: Search on vfs: games/eduke32
n: Search on vfs: games/eduke32/blood
n: Search on vfs: games/eduke32/duke3d
```

ideally if i set the only folder CG is allowed to look in then it shouldnt be able to look elsewhere on /home/
or i can just firejail sandbox so it doesnt have a choice...

**Comment by arrowgent** [comment]
note: firejail seems to have fixed the bin from scanning other directories for game data

**Comment by arrowgent** [comment]
https://github.com/gerstrong/Commander-Genius/tree/mastersrc/engine/CGameLauncher.h
https://github.com/gerstrong/Commander-Genius/tree/master/src/engine/CGameLauncher.cpp

https://github.com/gerstrong/Commander-Genius/tree/master/GsKit/base/utils/FindFile.h
https://github.com/gerstrong/Commander-Genius/tree/master/GsKit/base/utils/FindFile.cpp

**Comment by gerstrong** [comment]
Can you post or send me your CGLog.html and CGenius.cfg? We had that problem in the past, but it got solved. Also, did you build it yourself, if yes, which commit did you use? If not, where did you get the package?

What about the posted links? they only point to some files maybe related...
