### ISSUE TITLE
How do I use the external music/sfx?

### ISSUE THREAD

**Issue by NJW1979** [gerstrong/Commander-Genius#363]
I downloaded the latest addon pack and it has a lot of music replacements and better sfx.  How do I get CG to recognise them and use them in game.  What's the folder structure.  The folders are in C:\Commander Genius\global\  if that's incorrect can someone help me put them in the right place to enjuy the HQ pack.

**Comment by gerstrong** [comment]
Can you post your CGLog.html? It should tell you where to look. Maybe I can give a better hint then...

**Comment by NJW1979** [comment]
Sure.  Here it is.
https://www.mediafire.com/file/ur0cqdnddv8sh9u/CGLog.html/file

**Comment by gerstrong** [comment]
I see a problem here. You lib only supports WAVE, AIFF and VOC. I wonder why. Let me check our build configs.

**Comment by gerstrong** [comment]
Have you tried putting the global dir into your documents directory? There should be a subdir called Commander Genius where all your data is stored. Is that not correctly explained in the instructions?
