### ISSUE TITLE
Animation misalignment on Keen4+ with scaling

### ISSUE THREAD

**Issue by senneschall** [gerstrong/Commander-Genius#368]
The loading screen animation seems to not use the scale2x scaler when overlaying the animateds parts resulting in this:
![keen4misalignment](https://user-images.githubusercontent.com/14364389/174137341-7fd4a352-7a9b-4b00-953f-9a85b20ae457.jpg)
The hand parts are not properly scaled and also seem to be drawn on the position where the non-scaled image would be.

The relevant part of my cgenius.conf:
`[Video]`
`aspect = 4:3`
`gameHeight = 480`
`gameWidth = 640`
`height = 960`
`integerScaling = true`
`scale = 1`
`scaletype = scalex`
`width = 1280`

Version 3.1.1-Release

**Comment by gerstrong** [comment]
Should be fixed with version 3.5.1. Wanna give it another try?

**Comment by senneschall** [comment]
I finally found the time to test it. And can confirm that the misalignment is gone. Thanks!
